"""
Auto-generated by Test Generation Agent — fully expanded, fixtures corrected.
Source: tests/jira/PHIX-95866/mobile.test.md

PHIX-95866 — Time Tracking | Employer ability to reject time entry modifications.

═══════════════════════════════════════════════════════════════════════════════
ARCHITECTURE: TWO CR TYPES  (from TimeEntriesCards.tsx)
═══════════════════════════════════════════════════════════════════════════════
  isProposedEntry=true            → EE used "Add Time Entry" (new manual entry)
    Card label : "Manual Entry Pending for Approval"
    ER view    : Accept + Reject buttons on card
    Reject warn: "Rejecting this entry will permanently delete this time entry."
    EE view    : manualEntryPendingNotice ("This time entry is currently pending
                  manager approval…")
    EE cancel  : Delete via kebab menu (NOT a Cancel Request / Cancel Mods button)

  isProposedEntry=false + changeRequestIdentifier set
                              → EE edited an existing entry (modification CR)
    Card label : "Manual Entry Pending for Approval" (same header)
    ER view    : Accept + Reject inside the employee-modifications accordion
    Reject warn: "If rejected, the modifications will be discarded…"
    EE view    : Accordion "X modification(s) by employee" +
                  "Cancel Modifications" link (red) + tooltip
    EE cancel  : Tap "Cancel Modifications" → confirm dialog → "Yes"

═══════════════════════════════════════════════════════════════════════════════
ACCEPT FLOW  (CRITICAL: two-tap required)
═══════════════════════════════════════════════════════════════════════════════
  Tapping "Accept" on the card opens an intermediate UzioCommentModal:
    heading = "Accept employee time entry changes"  (acceptEmployeeTimeEntryHeading)
    action  = "Accept"
  Must tap "Accept" a second time inside the modal to complete the accept.
  MyTimesheetPage.accept_entry() handles both taps.

═══════════════════════════════════════════════════════════════════════════════
FIXTURE MAP
═══════════════════════════════════════════════════════════════════════════════
  pending_new_entry       Manager (mobile2) sees mobile1's new-entry CR.
                          TC-02, TC-03, TC-06, TC-07, TC-08, TC-18, TC-20,
                          TC-22, TC-23, TC-31.

  pending_modification    Manager (mobile2) sees mobile3's modification CR.
                          TC-09, TC-11, TC-12, TC-19, TC-21, TC-27.

  pending_new_entry (destructive accept):   TC-04.
  pending_modification (destructive accept): TC-05 (reject).
                  (TC-10 accepts modification via two-tap)

  ee_with_new_entry       Driver stays as mobile1 (new-entry EE perspective).
                          TC-13, TC-14, TC-29.

  ee_with_modification    Driver stays as mobile3, CLOCKED IN, with a
                          modification CR pending.  TC-16, TC-28.

  ee_has_modification_cr  Driver stays as mobile3, NOT clocked in, with a
                          modification CR pending.  TC-24, TC-25, TC-26,
                          TC-30, TC-31 (Modifications Cancelled history).

  No fixture: TC-01, TC-17, TC-R01, TC-R02, TC-R03, TC-R04, TC-R05.
"""

import pytest
from pages.dashboard_page import DashboardPage
from pages.time_tracking_page import TimeTrackingPage
from pages.timesheet_page import MyTimesheetPage, TeamTimesheetPage
from core.locators import (
    MyTimesheet, TimesheetHistory, TeamTimesheet, Drawer, TimeTracking,
)


@pytest.mark.jira
@pytest.mark.usefixtures("driver")
class TestPHIX95866:

    def _begin(self, test_id, name):
        self._current_test_id = test_id
        self._current_test_name = name
        self._heal_log = []

    def _collect(self, *pages):
        for p in pages:
            self._heal_log.extend(getattr(p, "heal_log", []))

    def _open_my_timesheet(self) -> MyTimesheetPage:
        dash = DashboardPage(self.driver)
        dash.open_drawer_and_tap(Drawer.MY_TIMESHEET, verify_any=[MyTimesheet.HEADING])
        ts = MyTimesheetPage(self.driver)
        ts.verify_loaded()
        return ts

    def _open_team_timesheet(self) -> TeamTimesheetPage:
        dash = DashboardPage(self.driver)
        dash.open_drawer_and_tap(Drawer.TEAM_TIMESHEET, verify_any=[TeamTimesheet.HEADING])
        ts = TeamTimesheetPage(self.driver)
        ts.verify_loaded()
        return ts

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 1 — My Timesheet basics
    # ═══════════════════════════════════════════════════════════════════════

    def test_tc01_my_timesheet_opens(self):
        """My Timesheet is accessible from the drawer and shows its heading."""
        self._begin("TC-01", "My Timesheet opens from drawer")
        ts = self._open_my_timesheet()
        assert ts.is_text_visible(MyTimesheet.HEADING, 5)
        ts.press_back()
        self._collect(ts)

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 2 — ER view: new manual entry card
    # ═══════════════════════════════════════════════════════════════════════

    def test_tc02_pending_new_entry_card_header(self, pending_new_entry):
        """
        Proposed new entry (isProposedEntry=true) card shows
        'Manual Entry Pending for Approval' header on the manager's My Timesheet.
        """
        self._begin("TC-02", "Proposed new entry card shows 'Manual Entry Pending for Approval'")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        assert ts.is_text_visible(MyTimesheet.MANUAL_ENTRY_PENDING_APPROVAL, 5), (
            "Expected 'Manual Entry Pending for Approval' header on new entry card"
        )
        ts.press_back()
        self._collect(ts)

    def test_tc03_er_sees_accept_reject_on_new_entry(self, pending_new_entry):
        """ER sees Accept and Reject buttons on the new-entry card."""
        self._begin("TC-03", "ER sees Accept and Reject buttons on proposed new entry card")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        assert ts.is_text_visible(MyTimesheet.ACCEPT, 5), "Accept button not visible"
        assert ts.is_text_visible(MyTimesheet.REJECT, 5), "Reject button not visible"
        ts.press_back()
        self._collect(ts)

    def test_tc04_er_accepts_new_entry(self, pending_new_entry):
        """
        ER accepts proposed new time entry.
        Accept flow: tap Accept on card → 'Accept employee time entry changes'
        modal appears → tap Accept again → entry card disappears.
        """
        self._begin("TC-04", "ER accepts proposed new time entry via accept modal")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.accept_entry()   # two-tap: card → modal → confirm
        assert not ts.is_text_visible(MyTimesheet.MANUAL_ENTRY_PENDING_APPROVAL, 5), (
            "Pending card still visible after acceptance"
        )
        ts.press_back()
        self._collect(ts)

    def test_tc05_er_rejects_new_entry_no_reason(self, pending_new_entry):
        """ER rejects proposed new entry without entering a reason or toggling email."""
        self._begin("TC-05", "ER rejects proposed new entry without reason or email")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.reject_entry()
        assert not ts.is_text_visible(MyTimesheet.MANUAL_ENTRY_PENDING_APPROVAL, 5), (
            "Pending card still visible after rejection"
        )
        ts.press_back()
        self._collect(ts)

    def test_tc06_reject_modal_new_entry_permanent_delete_warning(self, pending_new_entry):
        """
        Reject modal for a NEW manual entry shows the 'permanently delete' warning.
        This warning only appears when isProposedEntry=true.
        """
        self._begin("TC-06", "Reject modal shows permanent-delete warning for new entry")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.open_reject_modal()
        assert ts.is_text_visible(MyTimesheet.REJECT_MODAL_TITLE, 5), (
            "'Reject Time Entry' modal title not visible"
        )
        assert ts.is_text_visible(MyTimesheet.REJECT_WARNING_NEW_ENTRY, 5), (
            f"Expected permanent-delete warning: '{MyTimesheet.REJECT_WARNING_NEW_ENTRY}'"
        )
        ts.cancel_reject_modal()
        ts.press_back()
        self._collect(ts)

    def test_tc07_er_rejects_new_entry_with_reason(self, pending_new_entry):
        """ER rejects new entry after typing a reason text in the reject modal."""
        self._begin("TC-07", "ER rejects new entry with reason text entered in modal")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.reject_entry(reason="Incorrect hours entered")
        assert not ts.is_text_visible(MyTimesheet.MANUAL_ENTRY_PENDING_APPROVAL, 5), (
            "Pending card still visible after rejection with reason"
        )
        ts.press_back()
        self._collect(ts)

    def test_tc08_reject_modal_email_checkbox(self, pending_new_entry):
        """
        Reject modal contains 'Send email notification to employee' checkbox.
        ER can toggle it and complete the reject.
        """
        self._begin("TC-08", "ER toggles 'Send email notification to employee' in reject modal")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.open_reject_modal()
        assert ts.is_text_visible(MyTimesheet.SEND_EMAIL_NOTIFICATION, 5), (
            "'Send email notification to employee' checkbox not visible"
        )
        ts.tap(MyTimesheet.SEND_EMAIL_NOTIFICATION)
        ts.tap(MyTimesheet.REJECT)
        ts.dismiss_popup_if_present("Close", 5)
        ts.press_back()
        self._collect(ts)

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 3 — ER view: accept modal heading (critical two-tap verification)
    # ═══════════════════════════════════════════════════════════════════════

    def test_tc23_er_accept_modal_heading_new_entry(self, pending_new_entry):
        """
        When ER taps Accept on a new-entry card, an intermediate modal opens
        with heading 'Accept employee time entry changes'. Verifies the modal
        appears before proceeding to accept. This is a distinct UX step from
        the reject flow which has no such intermediate modal.
        """
        self._begin("TC-23", "ER accept modal shows 'Accept employee time entry changes' heading")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.open_accept_modal()     # tap card Accept → wait for modal heading
        assert ts.is_text_visible(MyTimesheet.ACCEPT_MODAL_HEADING, 5), (
            f"Expected modal heading: '{MyTimesheet.ACCEPT_MODAL_HEADING}'"
        )
        # Submit accept via second tap in modal
        ts.tap(MyTimesheet.ACCEPT)
        ts.dismiss_popup_if_present("Close", 5)
        ts.press_back()
        self._collect(ts)

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 4 — ER view: modification CR card
    # ═══════════════════════════════════════════════════════════════════════

    def test_tc09_er_sees_accept_reject_on_modification(self, pending_modification):
        """Pending modification card shows Accept and Reject for ER."""
        self._begin("TC-09", "Pending modification card shows Accept and Reject for ER")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        assert ts.is_text_visible(MyTimesheet.ACCEPT, 5), "Accept button not visible on modification card"
        assert ts.is_text_visible(MyTimesheet.REJECT, 5), "Reject button not visible on modification card"
        ts.press_back()
        self._collect(ts)

    def test_tc10_er_accepts_modification(self, pending_modification):
        """
        ER accepts pending modification via two-tap accept flow:
        card Accept → intermediate 'Accept employee time entry changes' modal → Accept.
        """
        self._begin("TC-10", "ER accepts pending modification via accept modal")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.accept_entry()
        assert not ts.is_text_visible(MyTimesheet.MANUAL_ENTRY_PENDING_APPROVAL, 5), (
            "Pending modification card still visible after acceptance"
        )
        ts.press_back()
        self._collect(ts)

    def test_tc11_er_rejects_modification(self, pending_modification):
        """ER rejects pending modification without a reason."""
        self._begin("TC-11", "ER rejects pending modification")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.reject_entry()
        assert not ts.is_text_visible(MyTimesheet.MANUAL_ENTRY_PENDING_APPROVAL, 5), (
            "Pending modification card still visible after rejection"
        )
        ts.press_back()
        self._collect(ts)

    def test_tc12_reject_modal_modification_revert_warning(self, pending_modification):
        """
        Reject modal for a MODIFICATION CR shows the 'modifications will be discarded'
        revert warning — NOT the permanent-delete warning. The two warnings are
        mutually exclusive based on isProposedEntry flag.
        """
        self._begin("TC-12", "Reject modal shows revert warning for modification (not delete)")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.open_reject_modal()
        assert ts.is_text_visible(MyTimesheet.REJECT_MODAL_TITLE, 5)
        assert ts.is_text_visible(MyTimesheet.REJECT_WARNING_MODIFICATION, 5), (
            f"Expected revert warning: '{MyTimesheet.REJECT_WARNING_MODIFICATION}'"
        )
        assert not ts.is_text_visible(MyTimesheet.REJECT_WARNING_NEW_ENTRY, 2), (
            "Permanent-delete warning shown for a modification — wrong CR type created"
        )
        ts.cancel_reject_modal()
        ts.press_back()
        self._collect(ts)

    def test_tc31_reject_modal_reason_label(self, pending_new_entry):
        """
        Reject modal contains a 'Reason' field label (i18n:
        timeEntries.rejectEmployeeTimeEntryHeading = 'Reason'). This is
        displayed as the commentLabel inside the UzioCommentModal.
        """
        self._begin("TC-31", "Reject modal contains 'Reason' label")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.open_reject_modal()
        assert ts.is_text_visible("Reason", 5), (
            "'Reason' label not visible in reject modal"
        )
        ts.cancel_reject_modal()
        ts.press_back()
        self._collect(ts)

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 5 — ER: edit disabled on pending entries
    # ═══════════════════════════════════════════════════════════════════════

    def test_tc18_er_cannot_edit_pending_new_entry(self, pending_new_entry):
        """
        ER tapping Edit on a pending new entry is blocked with the 'editDisabledManualEntryER'
        message: '…currently pending your approval and cannot be edited at this time…'
        """
        self._begin("TC-18", "ER cannot edit pending new entry — disabled message shown")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.tap(MyTimesheet.EDIT_TIME_ENTRY)
        assert ts.is_text_visible(
            "currently pending your approval and cannot be edited at this time",
            timeout=8
        ), "Edit-disabled message not shown for pending new entry (ER)"
        ts.dismiss_popup_if_present("Close", 3)
        ts.dismiss_popup_if_present("OK", 3)
        ts.press_back()
        self._collect(ts)

    def test_tc19_er_cannot_edit_pending_modification(self, pending_modification):
        """
        ER tapping Edit on a pending modification is blocked with the
        'editDisabledPendingModifER' message.
        """
        self._begin("TC-19", "ER cannot edit pending modification — disabled message shown")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.tap(MyTimesheet.EDIT_TIME_ENTRY)
        assert ts.is_text_visible(
            "currently pending your approval and cannot be edited further at this time",
            timeout=8
        ), "Edit-disabled message not shown for pending modification (ER)"
        ts.dismiss_popup_if_present("Close", 3)
        ts.dismiss_popup_if_present("OK", 3)
        ts.press_back()
        self._collect(ts)

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 6 — EE view: new manual entry
    # ═══════════════════════════════════════════════════════════════════════

    def test_tc13_ee_sees_pending_notice_not_accept_reject(self, ee_with_new_entry):
        """
        EE with a pending NEW manual entry (isManuallyAdded=true, !isManagerApprovalPage)
        sees the 'manualEntryPendingNotice' text:
          'This time entry is currently pending manager approval…'
        EE does NOT see Accept or Reject buttons — those belong to the manager only.
        """
        self._begin("TC-13", "EE sees pending-approval notice, NOT Accept/Reject")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        assert ts.is_text_visible(MyTimesheet.MANUAL_ENTRY_PENDING_NOTICE, 5), (
            f"Expected pending notice: '{MyTimesheet.MANUAL_ENTRY_PENDING_NOTICE}'"
        )
        assert not ts.is_text_visible(MyTimesheet.ACCEPT, 2), (
            "'Accept' should not be visible for EE on own entry"
        )
        assert not ts.is_text_visible(MyTimesheet.REJECT, 2), (
            "'Reject' should not be visible for EE on own entry"
        )
        ts.press_back()
        self._collect(ts)

    def test_tc14_ee_no_action_buttons_on_own_pending_new_entry(self, ee_with_new_entry):
        """
        EE's own pending new entry card has NO 'Cancel Request' button and NO
        'Cancel Modifications' action — the only way to remove a pending new entry
        is for the manager to reject it. EE's kebab only shows Edit (which is blocked).
        """
        self._begin("TC-14", "EE has no cancel action on own pending new entry")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        # The EE sees the pending notice text
        assert ts.is_text_visible(MyTimesheet.MANUAL_ENTRY_PENDING_NOTICE, 5), (
            "Pending notice not found — wrong account or entry not created"
        )
        # No cancel-request or cancel-modifications action is rendered for new entries
        assert not ts.is_text_visible("Cancel Request", 2), (
            "'Cancel Request' should NOT appear for a pending new time entry"
        )
        assert not ts.is_text_visible(MyTimesheet.CANCEL_MODIFICATIONS, 2), (
            "'Cancel Modifications' should NOT appear for a pending new time entry"
        )
        ts.press_back()
        self._collect(ts)

    def test_tc29_ee_edit_blocked_on_own_pending_new_entry(self, ee_with_new_entry):
        """
        EE tapping Edit on their own pending new entry gets
        'editDisabledManualEntryEE' message:
          'This time entry is currently pending manager approval and cannot be
           edited at this time. To make changes, you must delete the existing
           entry and create a new one.'
        """
        self._begin("TC-29", "EE edit blocked on own pending new entry")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.tap(MyTimesheet.EDIT_TIME_ENTRY)
        assert ts.is_text_visible(
            MyTimesheet.EDIT_DISABLED_NEW_ENTRY_EE,
            timeout=8
        ), f"Expected EE edit-disabled message: '{MyTimesheet.EDIT_DISABLED_NEW_ENTRY_EE}'"
        ts.dismiss_popup_if_present("Close", 3)
        ts.dismiss_popup_if_present("OK", 3)
        ts.press_back()
        self._collect(ts)

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 7 — EE view: modification CR
    # ═══════════════════════════════════════════════════════════════════════

    def test_tc15_ee_sees_cancel_modifications_for_own_modification_cr(self, ee_has_modification_cr):
        """
        EE who has an existing (real) time entry and has edited it now sees
        hasPendingEmployeeModification=true.  The entry card shows a
        'Cancel Modifications' link (red text) inside the pending-modifications
        accordion — NOT a 'Cancel Request' button.
        """
        self._begin("TC-15", "EE sees 'Cancel Modifications' link on own pending modification")
        ts = self._open_my_timesheet()
        ts.scroll_to_text(MyTimesheet.CANCEL_MODIFICATIONS, max_swipes=8)
        assert ts.is_text_visible(MyTimesheet.CANCEL_MODIFICATIONS, 5), (
            "'Cancel Modifications' link not visible for EE with pending modification"
        )
        ts.press_back()
        self._collect(ts)

    def test_tc24_ee_cancel_modifications_confirm_dialog(self, ee_has_modification_cr):
        """
        EE taps 'Cancel Modifications' → confirmation dialog appears with:
          'Your pending changes will be discarded, and the time entry will revert
           to its previous state. Do you want to continue?'
        Dialog has 'Yes' and 'No' buttons.  Test verifies the dialog shows —
        it does NOT confirm (so it does not consume the fixture's entry).
        """
        self._begin("TC-24", "EE cancel-modifications confirmation dialog appears")
        ts = self._open_my_timesheet()
        ts.scroll_to_text(MyTimesheet.CANCEL_MODIFICATIONS, max_swipes=8)
        ts.tap(MyTimesheet.CANCEL_MODIFICATIONS)
        assert ts.is_text_visible(MyTimesheet.CANCEL_CONFIRM_MESSAGE, 8), (
            "Cancel-modifications confirmation dialog not shown"
        )
        assert ts.is_text_visible(MyTimesheet.CANCEL_CONFIRM_YES, 3), (
            "'Yes' button not visible in confirm dialog"
        )
        assert ts.is_text_visible(MyTimesheet.NO, 3), (
            "'No' button not visible in confirm dialog"
        )
        # Dismiss without confirming — tap "No"
        ts.tap(MyTimesheet.NO)
        ts.press_back()
        self._collect(ts)

    def test_tc25_ee_cancels_modification_entry_disappears(self, ee_has_modification_cr):
        """
        EE completes cancel-modifications: taps 'Cancel Modifications' → 'Yes'.
        After confirmation the pending card disappears (no longer awaiting approval).
        This test CONSUMES the modification CR.
        """
        self._begin("TC-25", "EE cancels modification — pending card disappears")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.cancel_modification()    # Cancel Modifications → Yes → Close
        assert not ts.is_text_visible(MyTimesheet.MANUAL_ENTRY_PENDING_APPROVAL, 5), (
            "Pending modification card still visible after EE cancellation"
        )
        ts.press_back()
        self._collect(ts)

    def test_tc30_cancel_modifications_tooltip_visible(self, ee_has_modification_cr):
        """
        Inside the pending-modifications accordion, the 'cancelModificationsTooltip'
        italic text is visible:
          'Cancelling will discard the pending modifications and restore the
           time entry to its previous state.'
        """
        self._begin("TC-30", "Cancel Modifications tooltip visible in modification accordion")
        ts = self._open_my_timesheet()
        ts.scroll_to_text(MyTimesheet.CANCEL_MODIFICATIONS_TOOLTIP, max_swipes=8)
        assert ts.is_text_visible(MyTimesheet.CANCEL_MODIFICATIONS_TOOLTIP, 5), (
            f"Tooltip not visible: '{MyTimesheet.CANCEL_MODIFICATIONS_TOOLTIP}'"
        )
        ts.press_back()
        self._collect(ts)

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 8 — EE with pending CR: clock-out and add-time blocked
    # ═══════════════════════════════════════════════════════════════════════

    def test_tc16_ee_clock_out_blocked_pending_cr(self, ee_with_modification):
        """
        EE who is CLOCKED IN and has a pending modification CR taps Clock Out.
        A block modal appears with 'pendingCRClockOutBlocked' message (partial match):
          'You have pending modifications on this time entry that are awaiting
           manager approval.'
        """
        self._begin("TC-16", "EE with pending CR is blocked from clocking out")
        dash = DashboardPage(self.driver)
        tt = dash.open_time_tracking()
        assert tt.is_clocked_in(), (
            "Precondition failed: EE must be clocked in. Check ee_with_modification fixture."
        )
        tt.tap(TimeTracking.CLOCK_OUT)
        assert tt.is_text_visible(
            MyTimesheet.CLOCK_OUT_BLOCKED_PARTIAL,
            timeout=8
        ), "Clock-out block message not shown for EE with pending CR"
        self._collect(dash, tt)

    def test_tc28_clock_out_blocked_offers_cancel_and_clock_out(self, ee_with_modification):
        """
        The clock-out-blocked modal offers 'Cancel Modifications & Clock Out' action
        button — a single-tap shortcut to cancel the pending CR and clock out.
        Also verifies 'Dismiss' button is present (to close without action).
        """
        self._begin("TC-28", "Clock-out blocked modal offers 'Cancel Modifications & Clock Out'")
        dash = DashboardPage(self.driver)
        tt = dash.open_time_tracking()
        tt.tap(TimeTracking.CLOCK_OUT)
        # Block modal should appear
        tt.wait_for_text(MyTimesheet.CLOCK_OUT_BLOCKED_PARTIAL, 8)
        assert tt.is_text_visible(MyTimesheet.CANCEL_MODIFICATIONS_AND_CLOCK_OUT, 5), (
            "'Cancel Modifications & Clock Out' button not visible in block modal"
        )
        assert tt.is_text_visible(MyTimesheet.DISMISS, 3), (
            "'Dismiss' button not visible in block modal"
        )
        # Dismiss without taking action
        tt.tap(MyTimesheet.DISMISS)
        self._collect(dash, tt)

    def test_tc17_ee_add_time_blocked_pending_modification_cr(self, ee_has_modification_cr):
        """
        EE who has a pending modification CR taps 'Add Time Entry'.
        The backend returns the 'cannotAddTimePendingModifications' block:
          'Time cannot be added while modifications are pending manager
           approval or rejection. You can add time once the manager takes action.'
        Fixture: ee_has_modification_cr — mobile3 logged in, modification CR pending,
        NOT clocked in (so EE can access My Timesheet freely).
        """
        self._begin("TC-17", "EE with pending modification CR blocked from adding new time")
        ts = self._open_my_timesheet()
        ts.scroll_to_text(MyTimesheet.ADD_TIME_ENTRY, max_swipes=6)
        ts.tap(MyTimesheet.ADD_TIME_ENTRY)
        assert ts.is_text_visible(
            MyTimesheet.ADD_TIME_BLOCKED_PARTIAL,
            timeout=8
        ), f"Add-time block message not shown. Expected: '{MyTimesheet.ADD_TIME_BLOCKED_PARTIAL}'"
        ts.dismiss_popup_if_present("Close", 3)
        ts.dismiss_popup_if_present("OK", 3)
        ts.press_back()
        self._collect(ts)

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 9 — History events
    # ═══════════════════════════════════════════════════════════════════════

    def test_tc20_history_time_entry_rejected(self, pending_new_entry):
        """
        After ER rejects a new manual entry the history shows 'Time Entry Rejected'.
        """
        self._begin("TC-20", "History shows 'Time Entry Rejected' after new-entry rejection")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.reject_entry()
        ts.scroll_to_history_event(TimesheetHistory.TIME_ENTRY_REJECTED)
        assert ts.is_history_event_visible(TimesheetHistory.TIME_ENTRY_REJECTED, 5), (
            "'Time Entry Rejected' not found in history"
        )
        ts.press_back()
        self._collect(ts)

    def test_tc21_history_modifications_rejected(self, pending_modification):
        """
        After ER rejects a modification CR the history shows 'Modifications Rejected'.
        """
        self._begin("TC-21", "History shows 'Modifications Rejected' after edit rejection")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.reject_entry()
        ts.scroll_to_history_event(TimesheetHistory.MODIFICATIONS_REJECTED)
        assert ts.is_history_event_visible(TimesheetHistory.MODIFICATIONS_REJECTED, 5), (
            "'Modifications Rejected' not found in history"
        )
        ts.press_back()
        self._collect(ts)

    def test_tc22_history_time_entry_accepted(self, pending_new_entry):
        """
        After ER accepts a new manual entry (via two-tap accept modal flow)
        the history shows 'Time Entry Accepted'.
        """
        self._begin("TC-22", "History shows 'Time Entry Accepted' after acceptance")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.accept_entry()
        ts.scroll_to_history_event(TimesheetHistory.TIME_ENTRY_ACCEPTED)
        assert ts.is_history_event_visible(TimesheetHistory.TIME_ENTRY_ACCEPTED, 5), (
            "'Time Entry Accepted' not found in history"
        )
        ts.press_back()
        self._collect(ts)

    def test_tc27_history_modifications_accepted(self, pending_modification):
        """
        After ER accepts a modification CR (two-tap accept modal) the history shows
        'Modifications Accepted'.
        """
        self._begin("TC-27", "History shows 'Modifications Accepted' after modification acceptance")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.accept_entry()
        ts.scroll_to_history_event(TimesheetHistory.MODIFICATIONS_ACCEPTED)
        assert ts.is_history_event_visible(TimesheetHistory.MODIFICATIONS_ACCEPTED, 5), (
            "'Modifications Accepted' not found in history"
        )
        ts.press_back()
        self._collect(ts)

    def test_tc26_history_modifications_cancelled_by_ee(self, ee_has_modification_cr):
        """
        After EE cancels their own modification via 'Cancel Modifications' → 'Yes',
        the history shows 'Modifications Cancelled'.
        """
        self._begin("TC-26", "History shows 'Modifications Cancelled' after EE self-cancel")
        ts = self._open_my_timesheet()
        ts.scroll_to_pending_entry()
        ts.cancel_modification()    # Cancel Modifications → Yes
        ts.scroll_to_history_event(TimesheetHistory.MODIFICATIONS_CANCELLED)
        assert ts.is_history_event_visible(TimesheetHistory.MODIFICATIONS_CANCELLED, 5), (
            "'Modifications Cancelled' not found in history after EE self-cancel"
        )
        ts.press_back()
        self._collect(ts)

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 10 — Regression: adjacent flows must not be broken
    # ═══════════════════════════════════════════════════════════════════════

    def test_tc_r01_clock_in_out_cycle_regression(self):
        """Clock In → Clock Out cycle works end-to-end (PHIX-95866 regression)."""
        self._begin("TC-R01", "Clock In → Clock Out cycle still works (regression)")
        dash = DashboardPage(self.driver)
        tt = dash.open_time_tracking()
        tt.ensure_clocked_out()
        tt.clock_in()
        tt.wait_for_clocked_in(90)
        assert tt.is_clocked_in(), "Not clocked in after Clock In"
        tt.clock_out()
        tt.wait_for_clocked_out(60)
        assert tt.is_clock_in_button_visible(), "Clock In button not visible after Clock Out"
        self._collect(dash, tt)

    def test_tc_r02_my_timesheet_loads_normally(self):
        """My Timesheet loads without error when there are no pending CRs."""
        self._begin("TC-R02", "My Timesheet loads normally with no pending CRs")
        ts = self._open_my_timesheet()
        assert ts.is_text_visible(MyTimesheet.HEADING, 5)
        ts.press_back()
        self._collect(ts)

    def test_tc_r03_team_timesheet_accessible(self):
        """Team Timesheet still loads from drawer (regression — must not break for manager)."""
        self._begin("TC-R03", "Team Timesheet accessible from drawer (regression)")
        tts = self._open_team_timesheet()
        assert tts.is_text_visible(TeamTimesheet.HEADING, 5)
        tts.press_back()
        self._collect(tts)

    def test_tc_r04_add_time_entry_button_visible_no_pending_cr(self):
        """
        'Add Time Entry' button is visible on My Timesheet when there are no
        pending CRs — PHIX-95866 must not hide this button for manager accounts.
        """
        self._begin("TC-R04", "Add Time Entry button visible when no pending CR")
        ts = self._open_my_timesheet()
        ts.scroll_to_text(MyTimesheet.ADD_TIME_ENTRY, max_swipes=5)
        assert ts.is_text_visible(MyTimesheet.ADD_TIME_ENTRY, 5), (
            "'Add Time Entry' not visible — may have been accidentally hidden by PHIX-95866 changes"
        )
        ts.press_back()
        self._collect(ts)

    def test_tc_r05_time_tracking_unaffected_for_manager(self):
        """
        Time Tracking screen opens normally for manager account.
        Clock In button is present (manager has no pending CR to block it).
        """
        self._begin("TC-R05", "Time Tracking screen functional for manager (regression)")
        dash = DashboardPage(self.driver)
        tt = dash.open_time_tracking()
        tt.ensure_clocked_out()
        assert tt.is_clock_in_button_visible(), (
            "Clock In button not visible on Time Tracking for manager — unexpected block"
        )
        self._collect(dash, tt)
