"""
Mobile test-case Excel generator for MobileAutoQA.

Produces a polished .xlsx with THREE tabs:
  1. Summary             — ticket/feature meta + coverage totals
  2. Detail Test Cases   — full cases (one row each; ALL test steps in ONE cell)
  3. Regression Checklist— lightweight pass/fail tracker for manual runs

Design rules (adapted from the web qa-generate reference):
  - "Test Steps" is a SINGLE column — all steps numbered in one wrapped cell
    (never Step 1 / Step 2 / … as separate columns — that makes the sheet unusable).
  - Precondition has BOTH a one-line "what data" and full numbered steps
    (which screen + every tap to reach the state).
  - Mobile-specific columns: Platform (Android/iOS/Both), Role/Account, App Text/Locators.

Public API:
    from utils.testcase_excel import build_testcase_workbook
    build_testcase_workbook(out_path, meta, testcases)

`meta`  : dict — title, jira, source, generated_by, environment, app_build, notes
`testcases` : list[dict] — each with keys:
    id, title, module, platform, type, priority, role,
    precondition, precondition_steps (list[str]), steps (list[str]),
    expected, app_text (str), automation (str)
"""

from datetime import datetime
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ── palette ──────────────────────────────────────────────────────────────────
NAVY = "1F3864"
HEADER_FILL = PatternFill("solid", fgColor=NAVY)
HEADER_FONT = Font(color="FFFFFF", bold=True, size=11)
TITLE_FONT = Font(color=NAVY, bold=True, size=16)
SUB_FONT = Font(color="595959", size=10)
WRAP_TOP = Alignment(wrap_text=True, vertical="top")
CENTER = Alignment(horizontal="center", vertical="center", wrap_text=True)
THIN = Side(style="thin", color="D9D9D9")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

PRIORITY_FILL = {
    "P1": PatternFill("solid", fgColor="F8CBAD"),   # critical/high — orange
    "P2": PatternFill("solid", fgColor="FFE699"),   # medium — amber
    "P3": PatternFill("solid", fgColor="E2EFDA"),   # low — green
}
TYPE_FILL = {
    "E2E": PatternFill("solid", fgColor="D9E1F2"),
}

# Detail sheet columns: (header, width)
DETAIL_COLS = [
    ("TC ID", 10),
    ("Title", 34),
    ("Module / Feature", 18),
    ("Platform", 10),
    ("Type", 13),
    ("Priority", 9),
    ("Role / Account", 18),
    ("Precondition (data needed)", 28),
    ("Precondition Steps", 40),
    ("Test Steps", 60),
    ("Expected Result", 34),
    ("App Text / Locators", 26),
    ("Automation", 22),
]
CHECKLIST_COLS = [
    ("TC ID", 10), ("Title", 40), ("Module", 18), ("Platform", 10),
    ("Priority", 9), ("Type", 13), ("Status", 12), ("Run Date", 14), ("Notes", 40),
]


def _numbered(items):
    """Join a list of steps into ONE cell, numbered, newline-separated."""
    if not items:
        return ""
    if isinstance(items, str):
        return items
    out = [s for s in items if s and str(s).strip()]
    return "\n".join(f"{i+1}) {str(s).strip()}" for i, s in enumerate(out))


def _style_header(ws, ncols, row=1):
    for c in range(1, ncols + 1):
        cell = ws.cell(row=row, column=c)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = CENTER
        cell.border = BORDER


def _summary_sheet(wb, meta, testcases):
    ws = wb.active
    ws.title = "Summary"
    ws.sheet_view.showGridLines = False
    ws["A1"] = meta.get("title", "UZIO Mobile — Test Cases")
    ws["A1"].font = TITLE_FONT
    ws.merge_cells("A1:D1")

    rows = [
        ("Jira / Source", meta.get("jira") or meta.get("source", "—")),
        ("Generated", datetime.now().strftime("%Y-%m-%d %H:%M")),
        ("Generated by", meta.get("generated_by", "Test Generation Agent (MobileAutoQA)")),
        ("Environment", meta.get("environment", "—")),
        ("App build", meta.get("app_build", "—")),
        ("Total test cases", len(testcases)),
    ]
    r = 3
    for k, v in rows:
        ws.cell(row=r, column=1, value=k).font = Font(bold=True, color=NAVY)
        ws.cell(row=r, column=2, value=str(v))
        r += 1

    # Coverage breakdowns
    def _bucket(field, val):
        # Collapse the free-text Automation column into Automated/Planned/Manual
        if field == "automation":
            low = str(val).lower()
            if low.startswith("automated"):
                return "Automated"
            if low.startswith("planned"):
                return "Planned"
            if low.startswith("manual"):
                return "Manual"
        return val

    def _count(field):
        d = {}
        for tc in testcases:
            key = _bucket(field, tc.get(field, "—"))
            d[key] = d.get(key, 0) + 1
        return dict(sorted(d.items(), key=lambda x: -x[1]))

    r += 1
    for title, field in [("By Type", "type"), ("By Priority", "priority"),
                         ("By Module", "module"), ("By Platform", "platform"),
                         ("By Automation", "automation")]:
        ws.cell(row=r, column=1, value=title).font = Font(bold=True, color=NAVY)
        r += 1
        for k, v in _count(field).items():
            ws.cell(row=r, column=1, value=f"   {k}")
            ws.cell(row=r, column=2, value=v)
            r += 1
        r += 1

    if meta.get("notes"):
        ws.cell(row=r, column=1, value="Notes").font = Font(bold=True, color=NAVY)
        ws.cell(row=r + 1, column=1, value=meta["notes"]).alignment = WRAP_TOP
        ws.merge_cells(start_row=r + 1, start_column=1, end_row=r + 1, end_column=4)

    ws.column_dimensions["A"].width = 22
    ws.column_dimensions["B"].width = 60
    return ws


def _detail_sheet(wb, testcases):
    ws = wb.create_sheet("Detail Test Cases")
    ws.sheet_view.showGridLines = False
    for i, (h, w) in enumerate(DETAIL_COLS, start=1):
        ws.cell(row=1, column=1 + i - 1, value=h)
        ws.column_dimensions[get_column_letter(i)].width = w
    _style_header(ws, len(DETAIL_COLS))

    for r, tc in enumerate(testcases, start=2):
        vals = [
            tc.get("id", ""), tc.get("title", ""), tc.get("module", ""),
            tc.get("platform", "Both"), tc.get("type", ""), tc.get("priority", ""),
            tc.get("role", ""), tc.get("precondition", ""),
            _numbered(tc.get("precondition_steps")), _numbered(tc.get("steps")),
            tc.get("expected", ""), tc.get("app_text", ""), tc.get("automation", ""),
        ]
        for c, v in enumerate(vals, start=1):
            cell = ws.cell(row=r, column=c, value=v)
            cell.alignment = WRAP_TOP
            cell.border = BORDER
        # priority color on the Priority cell
        pcell = ws.cell(row=r, column=6)
        if pcell.value in PRIORITY_FILL:
            pcell.fill = PRIORITY_FILL[pcell.value]
            pcell.alignment = CENTER
        # platform centered
        ws.cell(row=r, column=4).alignment = CENTER
        # E2E row tint
        if str(tc.get("type", "")).upper().startswith("E2E"):
            for c in range(1, len(DETAIL_COLS) + 1):
                if c != 6:
                    ws.cell(row=r, column=c).fill = TYPE_FILL["E2E"]

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(DETAIL_COLS))}{len(testcases)+1}"
    return ws


def _checklist_sheet(wb, testcases):
    ws = wb.create_sheet("Regression Checklist")
    ws.sheet_view.showGridLines = False
    for i, (h, w) in enumerate(CHECKLIST_COLS, start=1):
        ws.cell(row=1, column=i, value=h)
        ws.column_dimensions[get_column_letter(i)].width = w
    _style_header(ws, len(CHECKLIST_COLS))
    for r, tc in enumerate(testcases, start=2):
        vals = [tc.get("id", ""), tc.get("title", ""), tc.get("module", ""),
                tc.get("platform", "Both"), tc.get("priority", ""), tc.get("type", ""),
                "", "", ""]  # Status / Run Date / Notes left blank for the tester
        for c, v in enumerate(vals, start=1):
            cell = ws.cell(row=r, column=c, value=v)
            cell.alignment = WRAP_TOP
            cell.border = BORDER
        pcell = ws.cell(row=r, column=5)
        if pcell.value in PRIORITY_FILL:
            pcell.fill = PRIORITY_FILL[pcell.value]
            pcell.alignment = CENTER
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(CHECKLIST_COLS))}{len(testcases)+1}"
    return ws


def build_testcase_workbook(out_path, meta, testcases):
    """Build the 3-tab test-case workbook and return the saved path."""
    wb = Workbook()
    _summary_sheet(wb, meta, testcases)
    _detail_sheet(wb, testcases)
    _checklist_sheet(wb, testcases)
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    wb.save(out)
    return str(out)
