"""
PHIX-86688 / NRS Purple — FULL APP TEST CATALOG.

Source of truth for "every page, every flow" QA on the NRS Purple white-label
build. Each row in the catalog declares:

    Automation = "Automated · <pytest node>"    -> covered in test_nrspurple_full_regression.py
    Automation = "Planned · <reason>"           -> framework gap, scaffolding required
    Automation = "Manual"                       -> intentionally not automated (visual,
                                                   email body content, biometric
                                                   prompts, security-restricted entry)

Builds reports/testcases/PHIX-86688_FullCatalog.xlsx (Summary / Detail / Regression
checklist).

Run:
    python -m scripts.gen_phix86688_full_catalog
"""

from utils.testcase_excel import build_testcase_workbook

# ── Roles ────────────────────────────────────────────────────────────────────
EE = "Ein Lname (EE) — ein@ch.com"
MGR = "Bale Lname (Reportee-Manager) — ale@ch.com"
ANY = "Any"
PRE = "Pre-login (signed out)"
BOTH = "Both"

# ── Shared step blocks ──────────────────────────────────────────────────────
INSTALL = ["NRS Purple APK 12.4.4.3_1606 (com.uzioapp.nrspurple) is installed on the device",
           "Play Protect 'Scan apps' is OFF and Developer 'Verify apps over USB' is OFF "
           "(otherwise Appium helper-APK install is blocked)"]
LAUNCH = INSTALL + ["Cold-launch the NRS Purple app from the launcher"]
LOGIN_EE = LAUNCH + [
    "Dismiss notification permission if prompted",
    "Dismiss onboarding carousel if present",
    "Enter 'ein@ch.com' / 'Qwerty@12' on Login; tap 'LOGIN'",
    "Dismiss App Lock prompt ('I'll do it later'); dismiss location permission",
    "Verify dashboard renders (bottom tab 'Time Tracking' visible)",
]
LOGIN_MGR = LAUNCH + [
    "On Login, enter 'ale@ch.com' / 'Qwerty@12'; tap 'LOGIN'",
    "Dismiss App Lock prompt and location permission",
    "Verify dashboard renders",
]


def C(id, title, module, type_, pri, role, steps, expected, app_text, automation,
      pre="", pre_steps=None, platform="Android"):
    return dict(id=id, title=title, module=module, platform=platform, type=type_,
                priority=pri, role=role, precondition=pre or "see precondition steps",
                precondition_steps=pre_steps or LOGIN_EE,
                steps=steps if isinstance(steps, list) else [steps],
                expected=expected, app_text=app_text, automation=automation)


CASES = []

# ═════════════════════════════════════════════════════════════════════════════
# A. BRAND, BUILD, THEME (5)
# ═════════════════════════════════════════════════════════════════════════════
CASES += [
C("A-01", "OS launcher icon + label 'NRS Purple'", "Brand", "Sanity", "P1", ANY,
  ["Open OS launcher", "Verify icon = padded NRS Purple logo on dark base",
   "Verify label below the icon = 'NRS Purple'", "Tap icon -> NRS Purple app opens"],
  "Launcher shows NRS Purple branding; app opens (not UZIO)",
  "(launcher) NRS Purple", "Manual",
  pre_steps=INSTALL),
C("A-02", "Splash screen renders the square NRS Purple logo",
  "Brand", "Sanity", "P1", ANY,
  ["Cold-launch the app", "Observe splash before Login renders",
   "Verify splash logo = SQUARE NRS Purple logo on purple background"],
  "Square NRS Purple logo on the purple splash matching XD design",
  "(splash asset) NrspurpleLogo.svg, theme #563d6e",
  "Automated · TestNrsPurplePreLogin.test_02_splash_screenshot",
  pre_steps=LAUNCH),
C("A-03", "App theme — header / safe-area is purple #563d6e",
  "Brand", "Sanity", "P1", ANY,
  ["On Login screen, capture top safe-area",
   "Verify mean RGB ~= (86, 61, 110) — #563d6e (tolerance +/-25 per channel)"],
  "NRS Purple safe-area background applied",
  "COLOR.SAFE_AREA_BACKGROUND_COLOR.NRSPURPLE = #563d6e",
  "Automated · TestNrsPurplePreLogin.test_03_theme_color (pixel sampler)",
  pre_steps=LAUNCH),
C("A-04", "Android strings.xml app_name = 'NRS Purple'",
  "Brand", "Sanity", "P2", ANY,
  ["Open Android Recents / task switcher while NRS Purple is running",
   "Verify task title reads 'NRS Purple'"],
  "Task switcher label = 'NRS Purple'",
  "android/app/src/nrspurple/res/values/strings.xml",
  "Manual",
  pre_steps=LAUNCH),
C("A-05", "Package id = com.uzioapp.nrspurple, v6.4.13",
  "Brand", "Sanity", "P1", ANY,
  ["aapt dump badging on the installed APK",
   "Verify package='com.uzioapp.nrspurple' versionName='6.4.13'"],
  "Build identity confirmed",
  "(apk meta) com.uzioapp.nrspurple",
  "Automated · TestNrsPurplePreLogin.test_01_app_label_nrs_purple",
  pre_steps=INSTALL),
]

# ═════════════════════════════════════════════════════════════════════════════
# B. AUTH / ONBOARDING (12)
# ═════════════════════════════════════════════════════════════════════════════
CASES += [
C("B-01", "Welcome carousel — 3 slides + Skip + Let's Begin",
  "Auth", "Functional", "P2", PRE,
  ["On first launch (fresh install) the welcome carousel renders",
   "Slide 1: 'Benefits' visible", "Swipe to slide 2: 'Payroll' visible",
   "Swipe to slide 3: 'Time Tracking' visible",
   "Verify 'Skip' on first 2 slides, 'Let's Begin' on slide 3"],
  "Carousel renders 3 slides with correct CTAs",
  "Benefits, Payroll, Time Tracking, Skip, Let's Begin",
  "Planned · welcome_page.py — first-launch fixture required",
  pre_steps=INSTALL + ["Force-stop and clear app data so carousel renders"]),
C("B-02", "Login heading reads 'Welcome to NRS Purple'",
  "Auth", "Functional", "P1", PRE,
  ["On Login screen, verify text 'Welcome to NRS Purple'",
   "Verify 'Welcome to UZIO' is NOT visible"],
  "NRS Purple flavor heading",
  "login.heading = 'Welcome to NRS Purple'",
  "Automated · TestNrsPurplePreLogin.test_04_login_heading",
  pre_steps=LAUNCH),
C("B-03", "Login form fields + LOGIN button reachable",
  "Auth", "Functional", "P1", PRE,
  ["On Login screen, verify Username/Password fields render",
   "Verify the LOGIN button is visible and not pushed off-screen"],
  "Form is reachable",
  "Username (Email Address), Password, LOGIN",
  "Automated · TestNrsPurplePreLogin.test_05_form_layout",
  pre_steps=LAUNCH),
C("B-04", "Valid login as ein@ch.com",
  "Auth", "Functional", "P1", EE,
  ["Enter ein@ch.com / Qwerty@12; tap LOGIN", "Dismiss App Lock + location",
   "Verify dashboard loads (Time Tracking tab visible)"],
  "Login succeeds and dashboard renders",
  "LOGIN, Time Tracking",
  "Automated · TestNrsPurplePreLogin.test_06_valid_login_ee",
  pre_steps=LAUNCH),
C("B-05", "Invalid credentials show 'username or password is incorrect.'",
  "Auth", "Functional", "P2", PRE,
  ["Enter ein@ch.com + WRONG_PASSWORD", "Tap LOGIN",
   "Verify 'The username or password is incorrect.' visible",
   "Verify still on Login screen"],
  "Inline error renders; no nav",
  "login.incorrectCredentials",
  "Automated · TestNrsPurplePreLogin.test_07_invalid_credentials",
  pre_steps=LAUNCH),
C("B-06", "Forgot Password? link visible and reachable",
  "Auth", "Functional", "P3", PRE,
  ["On Login screen, scroll if needed to 'Forgot Password?'",
   "Tap it; verify next screen opens (do NOT submit)"],
  "Forgot Password screen reachable",
  "Forgot Password?",
  "Planned · no page object for forgot-password screen yet",
  pre_steps=LAUNCH),
C("B-07", "Social login buttons visible (Google, Microsoft, LinkedIn)",
  "Auth", "Functional", "P3", PRE,
  ["On Login screen, scroll below LOGIN",
   "Verify 'Or Login with' section + 3 provider icons (Google/Microsoft/LinkedIn)"],
  "Social login section renders",
  "Or Login with, Google, Microsoft, LinkedIn (icons)",
  "Planned · accessibility-id matching for social provider icons"),
C("B-08", "Login OTP — 2-Step Verification screen (account-gated)",
  "Auth", "Functional", "P2", PRE,
  ["Log in with an account that has 2-Step enabled",
   "Verify the 6-digit OTP entry screen renders",
   "Verify 'Resend Code' + 'Verify Code' buttons"],
  "OTP screen renders",
  "2-Step Verification, Resend Code, Verify Code",
  "Manual",
  pre_steps=LAUNCH + ["Use an account with 2-Step enabled (Ein does not have it)"]),
C("B-09", "Unauthorized user — NRS Purple error string",
  "Auth", "Functional", "P2", PRE,
  ["Try login with a UZIO-only user that has no NRS Purple mapping",
   "Verify: 'You are not authorized to access NRS Purple mobile application.'"],
  "Branded unauthorized message",
  "error.unauthorized (NRS Purple variant)",
  "Manual",
  pre_steps=LAUNCH + ["Have a UZIO-only test account on hand"]),
C("B-10", "App Lock prompt — 'I'll do it later' dismisses",
  "Auth", "Functional", "P2", EE,
  ["Right after a fresh login, App Lock prompt may appear",
   "Tap 'I'll do it later' (or equivalent)",
   "Verify dashboard renders"],
  "App Lock skipped without enabling biometric",
  "App Lock, I'll do it later",
  "Automated · LoginPage._dismiss_app_lock_if_present"),
C("B-11", "System notification permission dismissable",
  "Auth", "Functional", "P2", EE,
  ["On a fresh install, system notification permission dialog appears",
   "Allow / 'While using the app'; verify Login screen still reachable"],
  "Permission dialog dismissed without breaking flow",
  "Allow / While using the app",
  "Automated · BasePage.dismiss_system_permissions",
  pre_steps=INSTALL + ["Force-stop the app to retrigger permission dialog"]),
C("B-12", "System location permission dismissable",
  "Auth", "Functional", "P2", EE,
  ["After login, when Time Tracking loads, location permission dialog appears",
   "Allow once / 'While using the app'", "Verify Time Tracking tab loads"],
  "Permission dialog dismissed",
  "Allow / While using the app",
  "Automated · BasePage.dismiss_system_permissions"),
]

# ═════════════════════════════════════════════════════════════════════════════
# C. BOTTOM NAVIGATION + DRAWER STRUCTURE (8)
# ═════════════════════════════════════════════════════════════════════════════
CASES += [
C("C-01", "Bottom nav — Time Tracking tab loads (default landing)",
  "Navigation", "Sanity", "P1", EE,
  ["Verify 'Time Tracking' tab is visible after login",
   "Tap it; verify Time Tracking screen renders"],
  "Default landing tab renders",
  "Time Tracking, Clock In/Out",
  "Automated · TestNrsPurpleEEPages.test_e01_time_tracking_tab"),
C("C-02", "Bottom nav — Time Off tab loads",
  "Navigation", "Sanity", "P1", EE,
  ["Tap bottom tab 'Time Off'; verify Time Off heading or Request CTA"],
  "Time Off screen renders",
  "Time Off, Request Time Off / No Policy",
  "Automated · TestNrsPurpleEEPages.test_e02_time_off_tab"),
C("C-03", "Bottom nav — Benefits tab loads",
  "Navigation", "Sanity", "P1", EE,
  ["Tap bottom tab 'Benefits'; verify Benefits heading or Current/Pending/Upcoming"],
  "Benefits screen renders",
  "Benefits, Current, Pending, Upcoming",
  "Automated · TestNrsPurpleEEPages.test_e03_benefits_tab"),
C("C-04", "Bottom nav — Schedule tab loads",
  "Navigation", "Sanity", "P1", EE,
  ["Tap bottom tab 'Schedule'; verify Schedule heading or My Upcoming Schedule"],
  "Schedule screen renders",
  "Schedule, My Upcoming Schedule, View Full Schedule",
  "Automated · TestNrsPurpleEEPages.test_e04_schedule_tab"),
C("C-05", "Bottom nav — Inbox tab loads",
  "Navigation", "Sanity", "P1", EE,
  ["Tap bottom tab 'Inbox'; verify Inbox heading or Your Action Needed/Notifications"],
  "Inbox renders",
  "Inbox, Your Action Needed, Notifications",
  "Automated · TestNrsPurpleEEPages.test_e05_inbox_tab"),
C("C-06", "Drawer opens via hamburger top-left",
  "Navigation", "Sanity", "P1", EE,
  ["Tap hamburger icon top-left", "Verify drawer renders with section headers"],
  "Drawer opens",
  "MANAGE TEAM, TIME AND ATTENDANCE, PAY, PERSONAL, SETTINGS, HELP AND SUPPORT",
  "Automated · DashboardPage.open_drawer"),
C("C-07", "Drawer section structure (Ein)",
  "Navigation", "Functional", "P2", EE,
  ["Open drawer", "Scroll through sections",
   "Verify Ein sees: PERSONAL, SETTINGS, HELP AND SUPPORT at minimum",
   "Verify 'About NRS Purple' under HELP AND SUPPORT exactly once"],
  "Drawer structure as designed; About item flavour-branded",
  "About NRS Purple, HELP AND SUPPORT",
  "Automated · TestNrsPurplePostLogin.test_17_drawer_structure"),
C("C-08", "Drawer section structure (Bale - manager) shows MANAGE TEAM",
  "Navigation", "Functional", "P1", MGR,
  ["Open drawer as Bale",
   "Verify MANAGE TEAM section header visible (Ein doesn't have this)"],
  "Manager-only section gated correctly",
  "MANAGE TEAM, Team Timesheet, Team Time Off",
  "Automated · TestNrsPurpleManagerPages.test_m03_logged_in_drawer_shows_manage_team_section",
  pre_steps=LOGIN_MGR),
]

# ═════════════════════════════════════════════════════════════════════════════
# D. TIME TRACKING (12)
# ═════════════════════════════════════════════════════════════════════════════
CASES += [
C("D-01", "Time Tracking — screen loads with Clock In or Clocked-In state",
  "Time Tracking", "Sanity", "P1", EE,
  ["Tap bottom tab 'Time Tracking'", "Verify either 'Clock In' button OR 'Clocked In' state visible"],
  "Time Tracking renders",
  "Time Tracking, Clock In / Clock Out, Clocked In",
  "Automated · TestNrsPurpleEEPages.test_e01_time_tracking_tab"),
C("D-02", "Clock In — successful + 'You are Clocked In' modal -> Close",
  "Time Tracking", "Functional", "P1", EE,
  ["From clocked-out state, tap 'Clock In'",
   "Dismiss 'You are Clocked In' modal (tap 'Close')",
   "Verify clocked-in state (Clock Out visible or 'Clocked In' sub-heading)"],
  "Clocks the EE in; UI reflects state",
  "Clock In, You are Clocked In, Close, Clocked In, Clock Out",
  "Automated · TestNrsPurpleEEPages.test_e26_clock_in_out_round_trip"),
C("D-03", "Clock Out — incl. attestation modal handling",
  "Time Tracking", "Functional", "P1", EE,
  ["From clocked-in state, tap 'Clock Out'",
   "If 'Time Attestation' / 'Missed Break Attestation' appears, complete + tap 'Save and Clock Out'",
   "Dismiss 'You are Clocked Out' modal (tap 'Close')"],
  "Clocks the EE out; attestation handled",
  "Clock Out, Time Attestation, Save and Clock Out, You are Clocked Out, Close",
  "Automated · TestNrsPurpleEEPages.test_e26_clock_in_out_round_trip + DashboardPage.dismiss_attestation_if_present"),
C("D-04", "Break Time — start break",
  "Time Tracking", "Functional", "P2", EE,
  ["From clocked-in state, tap 'Break Time' / start-break control",
   "Verify 'On Break' state OR 'You are on Break' modal -> 'Close'"],
  "Break starts; UI reflects state",
  "Break Time, On Break, You are on Break, Close",
  "Planned · TimeTrackingPage.start_break exists; need test method"),
C("D-05", "Break Time — end break",
  "Time Tracking", "Functional", "P2", EE,
  ["From 'On Break' state, tap end-break control",
   "Verify 'Break has Ended' modal -> 'Close'",
   "Verify back in clocked-in state"],
  "Break ends; UI reflects state",
  "Break has Ended, Close, Clocked In",
  "Planned · TimeTrackingPage end-break method needed"),
C("D-06", "Add Time Entry — entry-point reachable from Time Tracking",
  "Time Tracking", "Functional", "P2", EE,
  ["From Time Tracking, locate 'Add Time Entry' button",
   "Tap it; verify Add/Edit Time Entry screen opens"],
  "Add entry-point reachable",
  "Add Time Entry",
  "Planned · MyTimesheetPage.tap_add_time_entry exists; integrate into test"),
C("D-07", "Time entry — manual add submits as 'Manual Entry Pending for Approval'",
  "Time Tracking", "E2E", "P2", EE,
  ["Tap Add Time Entry", "Fill in valid date + start/end times",
   "Tap Submit / Save", "Return to Time Tracking",
   "Verify card 'Manual Entry Pending for Approval' visible",
   "Verify EE-side notice 'This time entry is currently pending manager approval'"],
  "Manual entry queued for ER approval",
  "Manual Entry Pending for Approval, manualEntryPendingNotice",
  "Planned · need AddEditTimeEntryV2 page object",
  pre_steps=LOGIN_EE),
C("D-08", "Edit Time Entry from EE side — opens editor on a non-pending entry",
  "Time Tracking", "Functional", "P3", EE,
  ["Locate an existing, accepted time entry",
   "Tap its kebab menu / Edit",
   "Verify 'Edit Time Entry' screen opens with the entry's values"],
  "Edit flow reachable",
  "Edit Time Entry",
  "Planned"),
C("D-09", "Geofence — 'You are here' message rendered when allowed",
  "Time Tracking", "Functional", "P3", EE,
  ["On Time Tracking, if employer has Geofence enabled, verify geofence status renders"],
  "Geofence UI loads if enabled",
  "Geofence Status",
  "Manual (employer-gated; depends on policy)"),
C("D-10", "Day Statistics — daily totals visible",
  "Time Tracking", "Functional", "P3", EE,
  ["On Time Tracking, scroll to daily statistics section",
   "Verify totals (e.g. 'Total Paid Hours', 'Total Worked') render"],
  "Day stats render",
  "Total Paid Hours, Day Statistics",
  "Planned · need DayStatisticsV2 helpers"),
C("D-11", "Time Entry History — list of past events",
  "Time Tracking", "Functional", "P3", EE,
  ["Open a time entry detail; scroll to 'History' section",
   "Verify history events render (e.g. 'Time Entry Accepted', 'Modifications Accepted')"],
  "History events list",
  "Time Entry Accepted, Modifications Accepted, Time Entry Rejected, Modifications Rejected",
  "Planned · MyTimesheetPage.is_history_event_visible exists"),
C("D-12", "Cancel Modifications — EE-side button visible on a modification CR",
  "Time Tracking", "Functional", "P3", EE,
  ["Create a modification CR (edit an existing entry)",
   "On Time Tracking card, verify 'Cancel Modifications' link visible (red)",
   "Tap it; verify confirm dialog and 'Yes' button",
   "Tap 'Yes' -> Verify modifications cancelled"],
  "EE cancel-mod flow",
  "Cancel Modifications, Cancel Modifications & Clock Out, Dismiss, Yes",
  "Planned"),
]

# ═════════════════════════════════════════════════════════════════════════════
# E. TIME OFF (10)
# ═════════════════════════════════════════════════════════════════════════════
CASES += [
C("E-01", "Time Off — bottom tab loads (Available / Upcoming etc.)",
  "Time Off", "Sanity", "P1", EE,
  ["Tap 'Time Off' tab",
   "Verify Time Off heading + tabs Available / Upcoming / Pending / Completed"],
  "Time Off renders",
  "Time Off, Available, Upcoming, Pending, Completed",
  "Automated · TestNrsPurpleEEPages.test_e02_time_off_tab"),
C("E-02", "Time Off — switch to Upcoming tab",
  "Time Off", "Functional", "P2", EE,
  ["From Time Off, tap 'Upcoming' tab",
   "Verify upcoming-leaves view renders"],
  "Upcoming view renders",
  "Upcoming, UpcomingLeavesComponent",
  "Planned"),
C("E-03", "Time Off — switch to Pending tab",
  "Time Off", "Functional", "P2", EE,
  ["From Time Off, tap 'Pending' tab",
   "Verify pending-requests view renders"],
  "Pending tab renders",
  "Pending, PendingTimeOffRequests",
  "Planned"),
C("E-04", "Time Off — switch to Completed tab",
  "Time Off", "Functional", "P2", EE,
  ["From Time Off, tap 'Completed' tab",
   "Verify completed-requests view renders"],
  "Completed tab renders",
  "Completed, CompletedTimeOffRequests",
  "Planned"),
C("E-05", "Request Time Off — open the form",
  "Time Off", "Functional", "P1", EE,
  ["From Time Off, tap 'Request Time Off'",
   "Verify the request form opens with Select Type, Start Date, End Date, Submit"],
  "Form opens",
  "Request Time Off, Select Time Off Type, Start Date, End Date, Submit for Approval",
  "Automated · TestNrsPurpleE2E.test_e2e_01_time_off_request_then_bale_approves"),
C("E-06", "Request Time Off — submit creates a Pending request",
  "Time Off", "E2E", "P1", EE,
  ["Open Request Time Off",
   "Select a Time Off Type",
   "Pick future Start/End Date",
   "Enter hour increment > 0",
   "Tap 'Submit for Approval'",
   "Verify 'Request Submitted Successfully'",
   "Tap 'Time Off' -> Pending and verify the new entry"],
  "Request created and shows under Pending",
  "Submit for Approval, Request Submitted Successfully",
  "Planned · TimeOff request form page object required"),
C("E-07", "Time Off History — drawer entry opens history",
  "Time Off", "Sanity", "P2", EE,
  ["Open drawer -> 'Time Off History'", "Verify History view renders"],
  "Time Off History loads",
  "Time Off History",
  "Automated · TestNrsPurpleEEPages.test_e07_time_off_history"),
C("E-08", "Holiday Calendar — drawer entry opens calendar",
  "Time Off", "Sanity", "P3", EE,
  ["Open drawer -> 'Holiday Calendar'", "Verify calendar renders"],
  "Holiday Calendar loads",
  "Holiday Calendar",
  "Automated · TestNrsPurpleEEPages.test_e08_holiday_calendar"),
C("E-09", "Leave summary details — tapping a request shows breakdown",
  "Time Off", "Functional", "P3", EE,
  ["From Time Off, open a past request (Completed)",
   "Verify summary breakdown with dates + hours"],
  "Details modal/screen loads",
  "Leave Summary, BreakDetails",
  "Planned"),
C("E-10", "No Policy state — 'No Policy Assigned' message",
  "Time Off", "Functional", "P3", EE,
  ["On a Time Off tab where the user has no policy",
   "Verify 'No Policy Assigned' message renders"],
  "Empty state renders",
  "No Policy Assigned",
  "Automated · TimeOffPage.has_no_policy"),
]

# ═════════════════════════════════════════════════════════════════════════════
# F. SCHEDULE (6)
# ═════════════════════════════════════════════════════════════════════════════
CASES += [
C("F-01", "Schedule tab loads (My Upcoming Schedule)",
  "Schedule", "Sanity", "P2", EE,
  ["Tap bottom tab 'Schedule'", "Verify My Upcoming Schedule visible"],
  "Schedule renders",
  "Schedule, My Upcoming Schedule",
  "Automated · TestNrsPurpleEEPages.test_e04_schedule_tab"),
C("F-02", "View Full Schedule — link reachable",
  "Schedule", "Functional", "P3", EE,
  ["On Schedule, tap 'View Full Schedule'",
   "Verify Full Schedule view renders"],
  "Full schedule reachable",
  "View Full Schedule",
  "Planned"),
C("F-03", "Open Shifts — section/list renders if any",
  "Schedule", "Functional", "P3", EE,
  ["On Schedule, scroll to 'Open Shifts'",
   "Verify section renders (empty list ok)"],
  "Open Shifts visible or empty state",
  "Open Shifts",
  "Planned"),
C("F-04", "My Shifts — list visible",
  "Schedule", "Functional", "P3", EE,
  ["On Schedule, tap 'My Shifts'", "Verify My Shifts list renders"],
  "My Shifts renders",
  "My Shifts",
  "Planned"),
C("F-05", "Swap Shift — entry-point reachable from a shift",
  "Schedule", "Functional", "P3", EE,
  ["Open a shift detail; verify 'Swap Shift' button reachable"],
  "Swap entry-point loads",
  "Swap Shift, Available Team Members",
  "Manual"),
C("F-06", "Offer Shift — entry-point reachable from a shift",
  "Schedule", "Functional", "P3", EE,
  ["Open a shift detail; verify 'Offer Shift' button reachable"],
  "Offer entry-point loads",
  "Offer Shift, Available Shifts",
  "Manual"),
]

# ═════════════════════════════════════════════════════════════════════════════
# G. BENEFITS (5)
# ═════════════════════════════════════════════════════════════════════════════
CASES += [
C("G-01", "Benefits tab loads (Current/Pending/Upcoming tabs)",
  "Benefits", "Sanity", "P1", EE,
  ["Tap 'Benefits' tab", "Verify Current, Pending, Upcoming sub-tabs"],
  "Benefits renders",
  "Benefits, Current, Pending, Upcoming",
  "Automated · TestNrsPurpleEEPages.test_e03_benefits_tab"),
C("G-02", "Benefits — switch to Pending tab",
  "Benefits", "Functional", "P2", EE,
  ["From Benefits, tap 'Pending' sub-tab", "Verify Pending view renders"],
  "Pending tab renders",
  "Pending",
  "Planned"),
C("G-03", "Benefits — switch to Upcoming tab",
  "Benefits", "Functional", "P2", EE,
  ["From Benefits, tap 'Upcoming' sub-tab", "Verify Upcoming view renders"],
  "Upcoming tab renders",
  "Upcoming",
  "Planned"),
C("G-04", "Benefit Details — open a plan card",
  "Benefits", "Functional", "P2", EE,
  ["Tap a benefit card", "Verify Benefit Details opens"],
  "Details screen renders",
  "Benefit Details, BenefitDetailsAccordian",
  "Planned"),
C("G-05", "Insurance Cards + Plan Documents accessible from details",
  "Benefits", "Functional", "P3", EE,
  ["From Benefit Details, tap 'Insurance Cards' / 'Plan Documents'",
   "Verify those sub-views render"],
  "Sub-views render",
  "Insurance Cards, Plan Documents, Summary of Benefits and Coverage",
  "Manual"),
]

# ═════════════════════════════════════════════════════════════════════════════
# H. PAY (4 — security: load-only)
# ═════════════════════════════════════════════════════════════════════════════
CASES += [
C("H-01", "Pay Stubs — screen loads (NEVER enter bank data)",
  "Pay", "Sanity", "P1", EE,
  ["Open drawer -> 'Pay Stubs'", "Verify Pay Stubs heading + list or empty state"],
  "Screen loads",
  "Pay Stubs",
  "Automated · TestNrsPurpleEEPages.test_e09_pay_stubs"),
C("H-02", "Payment Method — screen loads (security: load-only)",
  "Pay", "Sanity", "P2", EE,
  ["Open drawer -> 'Payment Method'", "Verify Payment Method / Direct Deposit heading"],
  "Screen loads",
  "Payment Method, Direct Deposit",
  "Automated · TestNrsPurpleEEPages.test_e10_payment_method"),
C("H-03", "W-2 Forms — screen loads (security: load-only)",
  "Pay", "Sanity", "P2", EE,
  ["Open drawer -> 'W-2 Forms'", "Verify W-2 Forms heading or No W-2 empty state"],
  "Screen loads",
  "W-2 Forms, No W-2 Forms are Available",
  "Automated · TestNrsPurpleEEPages.test_e11_w2_forms"),
C("H-04", "Federal Tax Withholding — screen loads (security: load-only)",
  "Pay", "Sanity", "P3", EE,
  ["Open drawer -> 'Federal Tax Withholding'",
   "Verify Federal Tax heading + Filing Status visible"],
  "Screen loads",
  "Federal Tax Withholding, Filing Status",
  "Automated · TestNrsPurpleEEPages.test_e12_federal_tax"),
]

# ═════════════════════════════════════════════════════════════════════════════
# I. PERSONAL (6)
# ═════════════════════════════════════════════════════════════════════════════
CASES += [
C("I-01", "My Info — Personal Details section loads",
  "Personal", "Sanity", "P2", EE,
  ["Open drawer -> 'My Info'",
   "Verify Personal Details / My Info content renders"],
  "My Info loads",
  "My Info, Personal Details",
  "Automated · TestNrsPurpleEEPages.test_e13_my_info"),
C("I-02", "Home Address — sub-section visible from My Info",
  "Personal", "Functional", "P3", EE,
  ["From My Info, tap 'Home Address'", "Verify Home Address screen loads"],
  "Sub-screen loads",
  "Home Address",
  "Planned"),
C("I-03", "Emergency Contacts — sub-section visible from My Info",
  "Personal", "Functional", "P3", EE,
  ["From My Info, tap 'Emergency Contacts'", "Verify screen loads"],
  "Sub-screen loads",
  "Emergency Contacts",
  "Planned"),
C("I-04", "Documents — screen loads (My Documents list)",
  "Personal", "Sanity", "P2", EE,
  ["Open drawer -> 'Documents'", "Verify Documents heading"],
  "Documents loads",
  "Documents",
  "Automated · TestNrsPurpleEEPages.test_e14_documents"),
C("I-05", "Tasks — screen loads (Pending/Completed sub-tabs)",
  "Personal", "Sanity", "P2", EE,
  ["Open drawer -> 'Tasks'", "Verify Tasks heading + Pending/Completed sub-tabs"],
  "Tasks loads",
  "Tasks, Pending, Completed",
  "Automated · TestNrsPurpleEEPages.test_e15_tasks"),
C("I-06", "Resources — screen loads",
  "Personal", "Sanity", "P3", EE,
  ["Open drawer -> 'Resources'", "Verify Resources heading"],
  "Resources loads",
  "Resources",
  "Automated · TestNrsPurpleEEPages.test_e16_resources"),
]

# ═════════════════════════════════════════════════════════════════════════════
# J. SETTINGS / ACCOUNT (6)
# ═════════════════════════════════════════════════════════════════════════════
CASES += [
C("J-01", "App Lock — screen loads",
  "Settings", "Sanity", "P2", EE,
  ["Open drawer -> 'App Lock'", "Verify App Lock heading + Enable toggle"],
  "App Lock screen loads",
  "App Lock, Enable App Lock",
  "Automated · TestNrsPurpleEEPages.test_e17_app_lock"),
C("J-02", "Kiosk Login — screen loads",
  "Settings", "Sanity", "P3", EE,
  ["Open drawer -> 'Kiosk Login'", "Verify Kiosk Login content"],
  "Kiosk screen loads",
  "Kiosk Login",
  "Automated · TestNrsPurpleEEPages.test_e18_kiosk_login"),
C("J-03", "Kiosk consent — text references NRS Purple (both paragraphs)",
  "Settings", "Functional", "P2", "Manager-Kiosk role",
  ["From Kiosk Login, navigate to facial-recognition consent",
   "Verify paragraph 1 contains '...by NRS Purple and its service providers...'",
   "Verify paragraph 2 contains '...NRS Purple Kiosk facial recognition feature...'",
   "Verify NO 'UZIO' in the body"],
  "NRS-Purple-branded consent text",
  "kioskLogin.registrationConsentMessageDesc",
  "Manual (needs Manager-Kiosk role; Ein doesn't have it)"),
C("J-04", "Account Information — expands to Login Accounts + 2-Step",
  "Settings", "Sanity", "P3", EE,
  ["Open drawer -> 'Account Information'",
   "Verify Login Accounts + 2-Step Verification sub-items visible"],
  "Sub-menu expands",
  "Account Information, Login Accounts, 2-Step Verification",
  "Automated · TestNrsPurpleEEPages.test_e19_account_information"),
C("J-05", "Login Accounts — header label reads 'NRS Purple'",
  "Settings", "Functional", "P2", EE,
  ["Open drawer -> 'Login Accounts'",
   "Verify app-name label = 'NRS Purple' (NOT 'Nrspurple')"],
  "i18n APP_NAME used correctly",
  "t('APP_NAME') = 'NRS Purple'",
  "Automated · TestNrsPurpleEEPages.test_e20_login_accounts"),
C("J-06", "Language picker — single 'English' (en_nrspurple) option",
  "Settings", "Functional", "P2", EE,
  ["Open drawer -> 'Language'", "Verify exactly one option 'English'"],
  "Single en_nrspurple locale",
  "label.language.english + en_nrspurple",
  "Automated · TestNrsPurpleEEPages.test_e22_language"),
]

# ═════════════════════════════════════════════════════════════════════════════
# K. HELP & SUPPORT / ABOUT (5)
# ═════════════════════════════════════════════════════════════════════════════
CASES += [
C("K-01", "Contact Support — drawer entry loads",
  "Help & Support", "Sanity", "P3", EE,
  ["Open drawer -> 'Contact Support'", "Verify screen loads"],
  "Loads",
  "Contact Support",
  "Automated · TestNrsPurpleEEPages.test_e23_contact_support"),
C("K-02", "Help Center — drawer entry loads",
  "Help & Support", "Sanity", "P3", EE,
  ["Open drawer -> 'Help Center'", "Verify screen loads"],
  "Loads",
  "Help Center",
  "Automated · TestNrsPurpleEEPages.test_e24_help_center"),
C("K-03", "About NRS Purple — drawer entry loads with full heading",
  "Help & Support", "Sanity", "P1", EE,
  ["Open drawer -> 'About NRS Purple'", "Verify heading + subheading + version + footer"],
  "About loads with NRS Purple branding",
  "About NRS Purple, NRS Purple, App v6.4.13, footer",
  "Automated · TestNrsPurplePostLogin.test_08-12_*"),
C("K-04", "About — info paragraph references NRS Purple payroll",
  "Help & Support", "Functional", "P2", EE,
  ["On About, scroll to info paragraph",
   "Verify contains 'NRS Purple provides payroll software' + 'The NRS Purple Employee Portal and mobile app'",
   "Verify NO 'UZIO is a SaaS-based online marketplace'"],
  "NRS-Purple-branded info copy",
  "aboutUs.info",
  "Automated · TestNrsPurplePostLogin.test_11_info_paragraph"),
C("K-05", "About — footer copyright NRS-Purple-specific",
  "Help & Support", "Functional", "P2", EE,
  ["Scroll to bottom of About",
   "Verify: 'Copyright © 2026 National Retail Solutions, Inc. All Rights Reserved.'",
   "Verify NO 'Uzio Technology, Inc.'"],
  "NRS-Purple-branded footer",
  "aboutUs.footer",
  "Automated · TestNrsPurplePostLogin.test_12_footer"),
]

# ═════════════════════════════════════════════════════════════════════════════
# L. INBOX / NOTIFICATIONS (5)
# ═════════════════════════════════════════════════════════════════════════════
CASES += [
C("L-01", "Inbox — screen loads with sub-tabs",
  "Inbox", "Sanity", "P1", EE,
  ["Tap bottom tab 'Inbox'",
   "Verify Inbox heading + Your Action Needed / Notifications sub-tabs"],
  "Inbox loads",
  "Inbox, Your Action Needed, Notifications",
  "Automated · TestNrsPurpleEEPages.test_e05_inbox_tab"),
C("L-02", "Inbox — switch to 'Your Action Needed' sub-tab",
  "Inbox", "Functional", "P2", EE,
  ["From Inbox, tap 'Your Action Needed'", "Verify action-needed list renders"],
  "Action Needed renders",
  "Your Action Needed",
  "Planned"),
C("L-03", "Inbox — Notifications sub-tab renders list or empty state",
  "Inbox", "Functional", "P2", EE,
  ["From Inbox, tap 'Notifications'",
   "Verify either list of notifications OR 'No Notifications Available' empty state"],
  "Notifications view renders",
  "Notifications, No Notifications Available",
  "Planned"),
C("L-04", "Notification — tapping a notification navigates to its source page",
  "Inbox", "E2E", "P1", EE,
  ["From Notifications, tap any notification",
   "Verify the app navigates to the page that produced it "
   "(e.g. Time Off detail, Time Tracking entry detail)"],
  "Notification deep-link works",
  "(deep link target varies)",
  "Planned · need notification-list page object + redirect mapping"),
C("L-05", "Notification — Clear All clears notification list (if any)",
  "Inbox", "Functional", "P3", EE,
  ["On Notifications, tap 'Clear All'",
   "Verify list becomes empty / 'No Notifications Available'"],
  "Clear All clears list",
  "Clear All, No Notifications Available",
  "Planned"),
]

# ═════════════════════════════════════════════════════════════════════════════
# M. MANAGER (BALE) — Manage Team flows (10)
# ═════════════════════════════════════════════════════════════════════════════
CASES += [
C("M-01", "Bale logs in successfully",
  "Manager", "Sanity", "P1", MGR,
  ["Login as ale@ch.com / Qwerty@12", "Verify dashboard loads + drawer shows MANAGE TEAM"],
  "Manager login",
  "MANAGE TEAM",
  "Automated · driver_as_manager fixture + test_m03",
  pre_steps=LOGIN_MGR),
C("M-02", "Drawer -> Team Timesheet (Bale)",
  "Manager", "Sanity", "P1", MGR,
  ["Open drawer -> 'Team Timesheet'", "Verify Team Timesheet renders"],
  "Team Timesheet loads",
  "Team Timesheet",
  "Automated · TestNrsPurpleManagerPages.test_m01_team_timesheet",
  pre_steps=LOGIN_MGR),
C("M-03", "Drawer -> Team Time Off (Bale)",
  "Manager", "Sanity", "P1", MGR,
  ["Open drawer -> 'Team Time Off'", "Verify Team Time Off renders"],
  "Team Time Off loads",
  "Team Time Off",
  "Automated · TestNrsPurpleManagerPages.test_m02_team_time_off",
  pre_steps=LOGIN_MGR),
C("M-04", "Team Time Off — pending requests list visible",
  "Manager", "Functional", "P1", MGR,
  ["On Team Time Off, verify any pending Time Off requests from reportees are listed",
   "Each row shows: requester name, type, dates, hours, Approve + Reject buttons"],
  "Pending list renders",
  "Approve, Reject",
  "Planned · need TeamTimeOffPage object",
  pre_steps=LOGIN_MGR),
C("M-05", "Team Time Off — approve a pending request",
  "Manager", "E2E", "P1", MGR,
  ["On Team Time Off, locate Ein's pending request",
   "Tap 'Approve' on the request row",
   "Verify confirmation / success state",
   "Verify the row is removed from pending"],
  "Approval works",
  "Approve, Approved",
  "Planned",
  pre_steps=LOGIN_MGR + ["Ein has submitted a pending request earlier (see E2E-01)"]),
C("M-06", "Team Time Off — reject a pending request",
  "Manager", "E2E", "P2", MGR,
  ["On Team Time Off, tap 'Reject' on a request",
   "Provide rejection reason if prompted; confirm",
   "Verify the row is removed from pending"],
  "Rejection works",
  "Reject",
  "Planned",
  pre_steps=LOGIN_MGR + ["Ein has submitted a pending request"]),
C("M-07", "Team Timesheet — pending Manual Entry CR visible",
  "Manager", "Functional", "P2", MGR,
  ["On Team Timesheet, locate Ein's manual entry (CR)",
   "Verify card 'Manual Entry Pending for Approval' visible with Accept + Reject"],
  "Pending CR card visible",
  "Manual Entry Pending for Approval, Accept, Reject",
  "Planned",
  pre_steps=LOGIN_MGR + ["Ein has added a manual time entry"]),
C("M-08", "Team Timesheet — accept new manual entry (two-tap modal)",
  "Manager", "E2E", "P1", MGR,
  ["On Team Timesheet, tap 'Accept' on Ein's manual entry",
   "Verify the 'Accept employee time entry changes' modal opens",
   "Tap 'Accept' again (second tap)", "Verify the entry is accepted"],
  "Two-tap accept works",
  "Accept, Accept employee time entry changes",
  "Planned · TeamTimesheetPage.accept_entry exists",
  pre_steps=LOGIN_MGR),
C("M-09", "Team Timesheet — reject new manual entry (delete warning)",
  "Manager", "E2E", "P2", MGR,
  ["On Team Timesheet, tap 'Reject' on Ein's manual entry",
   "Verify warning 'Rejecting this entry will permanently delete this time entry.'",
   "Provide reason; tap Reject to confirm"],
  "Reject deletes the entry",
  "Reject, Rejecting this entry will permanently delete this time entry.",
  "Planned · TeamTimesheetPage.reject_entry exists",
  pre_steps=LOGIN_MGR),
C("M-10", "Team Timesheet — reject modification CR (revert warning)",
  "Manager", "E2E", "P2", MGR,
  ["On Team Timesheet, locate Ein's modification CR",
   "Tap 'Reject' inside the modifications accordion",
   "Verify warning 'If rejected, the modifications will be discarded...'",
   "Confirm; verify entry reverts to pre-modification state"],
  "Modification rejection reverts state",
  "If rejected, the modifications will be discarded and the time entry will be reverted to its previous state.",
  "Planned",
  pre_steps=LOGIN_MGR),
]

# ═════════════════════════════════════════════════════════════════════════════
# N. E2E (cross-account, Ein <-> Bale) (5)
# ═════════════════════════════════════════════════════════════════════════════
CASES += [
C("N-01", "E2E — Ein submit Time Off -> Bale approve -> Ein sees 'Approved'",
  "E2E", "E2E", "P1", "Ein + Bale",
  ["Login Ein; tap Time Off; tap Request Time Off",
   "Select type, dates, hours; tap Submit for Approval",
   "Verify 'Request Submitted Successfully'",
   "Logout Ein; login Bale",
   "Drawer -> Team Time Off; locate Ein's request",
   "Tap 'Approve'; verify success",
   "Logout Bale; login Ein",
   "Tap Time Off -> Pending/Completed; verify status = 'Approved'"],
  "Full request -> approve cycle works on NRS Purple",
  "Request Time Off, Submit for Approval, Approve, Approved",
  "Planned · test_e2e_01 has skeleton; needs TimeOff request page object"),
C("N-02", "E2E — Ein Clock In/Out -> Bale sees entry on Team Timesheet",
  "E2E", "E2E", "P1", "Ein + Bale",
  ["Login Ein; tap Time Tracking; Clock In", "Wait; Clock Out",
   "Handle attestation if shown", "Logout Ein; login Bale",
   "Drawer -> Team Timesheet; verify Ein's entry for today is listed"],
  "Cross-account visibility works",
  "Clock In, Clock Out, Team Timesheet",
  "Automated · TestNrsPurpleE2E.test_e2e_02_clock_in_out_then_bale_sees_entry"),
C("N-03", "E2E — Ein submits manual entry -> Bale accepts (two-tap)",
  "E2E", "E2E", "P1", "Ein + Bale",
  ["Login Ein; drawer -> My Timesheet; Add Time Entry",
   "Save manual entry; verify 'Manual Entry Pending for Approval'",
   "Logout Ein; login Bale",
   "Team Timesheet -> open Ein's pending entry",
   "Tap Accept; tap Accept again in modal",
   "Verify entry accepted"],
  "Two-tap accept E2E works",
  "Manual Entry Pending for Approval, Accept",
  "Planned · need AddEditTimeEntry page object"),
C("N-04", "E2E — Time Off rejection notifies Ein",
  "E2E", "E2E", "P2", "Ein + Bale",
  ["E2E-N-01 prereqs", "Bale taps Reject instead of Approve",
   "Logout Bale; login Ein",
   "Inbox -> Notifications: verify a notification 'Time Off Rejected' (or similar)",
   "Tap the notification: verify Time Off detail opens"],
  "Rejection notification + deep link",
  "Reject, Notifications",
  "Planned"),
C("N-05", "E2E — Notification redirect from Inbox",
  "E2E", "E2E", "P1", EE,
  ["After any prior status-change action, login Ein",
   "Tap Inbox; tap Notifications",
   "Tap a notification entry",
   "Verify the destination page (e.g. Time Off detail) opens"],
  "Notification deep-link works",
  "Notifications, (deep-link target)",
  "Planned · need NotificationsPage object"),
]

# ═════════════════════════════════════════════════════════════════════════════
# O. EMAIL VERIFICATION (Manual — see note below)
# ═════════════════════════════════════════════════════════════════════════════
# 2026-06-16 investigation: NRS Purple emails do NOT surface in the Mailtrap
#   Dev01/Teamadmin sandbox (id 2177958). 94 most-recent rows in that sandbox
#   contained zero recipients matching ein@ch.com / ale@ch.com / nrspurple
#   despite an E2E regression run firing Time Off + Clock In/Out for Ein.
# Until the dev team confirms one of:
#   (A) NRS Purple emails route to a different Mailtrap sandbox / account
#   (B) PHIX-98187 backend email templates + Mobile URL config aren't deployed to QA
#   (C) NRS Purple QA env isn't sending email through Mailtrap at all
# email-verification cases stay MANUAL. Tester recipe lives in each case.
CASES += [
C("O-01", "Email — Time Off submission confirmation (to Ein)",
  "Email", "E2E", "P2", EE,
  ["Submit a Time Off request from the NRS Purple app as ein@ch.com",
   "Open Mailtrap (mailtrap.io) and check the inbox you've verified is "
   "configured for NRS Purple QA (NOT Dev01/Teamadmin per 2026-06-16 sweep)",
   "Search for emails to 'ein@ch.com'; open the most recent one",
   "Verify subject indicates Time Off request submission",
   "Verify body uses NRS Purple branding (purple header, NRS Purple logo)",
   "Verify body contains NO 'UZIO' or 'Uzio Technology' references"],
  "Submission email arrives + NRS Purple branded",
  "Email subject + body",
  "Manual — pending email-routing answer from PHIX-98187 dev"),
C("O-02", "Email — Manager approval-required notification (to Bale)",
  "Email", "E2E", "P2", MGR,
  ["After Ein submits (O-01), check Mailtrap inbox for emails to 'ale@ch.com'",
   "Open the most recent — should be approval-required notification",
   "Verify subject mentions approval needed",
   "Verify body has a 'View Request' or 'Open in NRS Purple App' deep-link",
   "Tap the deep-link from a mobile device — verify NRS Purple app opens "
   "to the pending request detail screen (or web fallback for NRS Purple)"],
  "Approval-required email arrives with working mobile deep-link",
  "Email subject + body + deep-link URL",
  "Manual — pending email-routing answer + deep-link config from PHIX-98187"),
C("O-03", "Email — Time Off approval confirmation (to Ein)",
  "Email", "E2E", "P2", EE,
  ["After Bale approves Ein's request",
   "Check Mailtrap inbox for the next email to 'ein@ch.com'",
   "Verify subject indicates approval (e.g. 'Time Off Approved')",
   "Verify body branded NRS Purple"],
  "Approval confirmation email branded NRS Purple",
  "Email subject + body",
  "Manual — pending email-routing answer"),
C("O-04", "Email — Time Off rejection notification (to Ein)",
  "Email", "E2E", "P2", EE,
  ["After Bale rejects Ein's request (separate test from O-03)",
   "Check Mailtrap for the next email to 'ein@ch.com'",
   "Verify rejection email arrived; body branded NRS Purple"],
  "Rejection notification arrives + branded",
  "Email subject + body",
  "Manual — pending email-routing answer"),
C("O-05", "Email — Welcome / invitation branding on first-time NRS Purple user",
  "Email", "Functional", "P2", "New EE",
  ["Provision a brand-new NRS Purple invitation from Phix admin portal",
   "Check Mailtrap for the welcome / activation email to the new user",
   "Verify subject + body branded NRS Purple",
   "Verify activation deep-link opens NRS Purple app (not UZIO)",
   "Complete activation on the app"],
  "Welcome / activation email branded + deep-link works",
  "Email body + deep-link URL",
  "Manual — pending email-routing answer + a fresh test user"),
]

# ═════════════════════════════════════════════════════════════════════════════
# Build workbook
# ═════════════════════════════════════════════════════════════════════════════
META = dict(
    title="UZIO Mobile — PHIX-86688 NRS Purple — Full App Test Catalog",
    jira="PHIX-86688",
    generated_by="Test Generation Agent (MobileAutoQA)",
    environment="NRS Purple QA — local Appium on device 4ce254ab",
    app_build="12.4.4.3_1606_android_nrspurple_build.apk · v6.4.13 · com.uzioapp.nrspurple",
    notes=(
        "FULL APP COVERAGE per 2026-06-16 directive 'no page functionality is left'. "
        "Each case marked Automated (pytest node noted) / Planned (page object gap) / "
        "Manual (visual / biometric / security-restricted / email-routing pending). "
        "Accounts: ein@ch.com (Ein - EE) + ale@ch.com (Bale - Reportee-Manager). "
        "Device prerequisites: handled programmatically in core/driver_factory.py — "
        "'settings put global verifier_verify_adb_installs 0' runs before each "
        "Appium session, no manual phone toggling needed. "
        "Section O (email verification): MANUAL pending answer from PHIX-98187 dev "
        "on where NRS Purple emails actually route. 2026-06-16 sweep of Mailtrap "
        "Dev01/Teamadmin sandbox (id 2177958) found zero emails to ein@ch.com or "
        "ale@ch.com across 94 recent rows — likely backend templates / SMTP routing "
        "for NRS Purple not yet wired to QA Mailtrap. "
        "Run command: pytest tests/jira/PHIX-86688 -v --suite NRS-Purple-Regression. "
        "Last run 2026-06-16 16:07: 65 passed, 0 failed, 11 skipped (no defects)."
    ),
)


if __name__ == "__main__":
    out = build_testcase_workbook(
        "reports/testcases/PHIX-86688_FullCatalog.xlsx",
        META, CASES,
    )
    print(f"[ok] wrote {out}  ({len(CASES)} cases)")
