"""
Generate the detailed UZIO Mobile SANITY test-case Excel from the structured
case list below. Mirrors tests/sanity/sanity.test.md (43 cases) but in the rich,
manual-QA-friendly Excel format (Summary + Detail Test Cases + Regression Checklist).

Run:
    python -m scripts.gen_sanity_testcases
Output:
    reports/testcases/UZIO_Mobile_Sanity_Testcases.xlsx

This file is also the reference template the Test Generation Agent follows when
producing per-Jira test-case workbooks.
"""

from utils.testcase_excel import build_testcase_workbook

# Reusable precondition blocks ------------------------------------------------
LOGGED_IN = [
    "Launch UZIO app on the device/BrowserStack",
    "Dismiss notification permission if prompted (Allow / While using the app)",
    "If the 3-screen onboarding carousel shows, tap 'Skip' (or swipe to 'Let's Begin')",
    "Enter username into field[0] and password into field[1]",
    "Tap 'LOGIN'",
    "On 'Enable App Lock' prompt tap \"I'll do it later\"",
    "Dismiss location permission if prompted (While using the app)",
    "Verify the 'Time Tracking' tab (bottom nav) is visible = logged in",
]
ON_TT = LOGGED_IN + ["Tap the 'Time Tracking' bottom tab"]

MGR = "Manager — mobile2@t.com"
EE_MANUAL = "Employee — mobile1@t.com"
EE_MOD = "Reportee/EE — mobile3@t.com"
ANY = "Any employee"

# Each case: id,title,module,platform,type,priority,role,precondition,
#            precondition_steps, steps, expected, app_text, automation
CASES = [
    # ── AUTH & APP ENTRY ──────────────────────────────────────────────────
    dict(id="MS-01", title="App launch & login lands on dashboard", module="Auth",
         platform="Both", type="Sanity", priority="P1", role=ANY,
         precondition="App installed; valid employee credentials",
         precondition_steps=["App installed / APK·IPA uploaded to BrowserStack"],
         steps=LOGGED_IN,
         expected="Dashboard loads with bottom nav; 'Time Tracking' tab visible",
         app_text="LOGIN, Time Tracking, I'll do it later",
         automation="Automated · test_ms01_app_launch_and_login"),
    dict(id="MS-02", title="Login with valid credentials (fresh)", module="Auth",
         platform="Both", type="Functional", priority="P1", role=ANY,
         precondition="Logged out; on login screen",
         precondition_steps=["Ensure logged out (login screen reachable)"],
         steps=["Dismiss permissions / onboarding carousel",
                "Wait for 'LOGIN' button", "Enter username into field[0]",
                "Enter password into field[1]", "Tap 'LOGIN'",
                "Dismiss 'Enable App Lock' via \"I'll do it later\"",
                "Dismiss location permission if shown",
                "Wait for 'Time Tracking' tab"],
         expected="Authentication succeeds; dashboard shown",
         app_text="Username (Email Address), Password, LOGIN",
         automation="Planned (covered indirectly by MS-01 already-logged-in path)"),
    dict(id="MS-05", title="Login validation — empty email blocks submit", module="Auth",
         platform="Both", type="Edge", priority="P2", role=ANY,
         precondition="On login screen, email empty",
         precondition_steps=["Reach login screen"],
         steps=["Clear field[0] (email)", "Tap 'LOGIN'",
                "Observe validation message"],
         expected="Inline validation: 'Please enter your e-mail to continue' (build-specific)",
         app_text="Please enter your e-mail to continue",
         automation="Planned"),
    dict(id="MS-06", title="Login validation — empty password blocks submit", module="Auth",
         platform="Both", type="Edge", priority="P2", role=ANY,
         precondition="On login screen, email entered, password empty",
         precondition_steps=["Reach login screen"],
         steps=["Enter username into field[0]", "Clear field[1] (password)",
                "Tap 'LOGIN'", "Observe validation message"],
         expected="Inline validation: 'Please enter your password to continue'",
         app_text="Please enter your password to continue",
         automation="Planned"),
    dict(id="MS-07", title="Login — invalid credentials show error", module="Auth",
         platform="Both", type="Edge", priority="P2", role=ANY,
         precondition="On login screen",
         precondition_steps=["Reach login screen"],
         steps=["Enter 'wrong@t.com' into field[0]",
                "Enter 'WrongPass123' into field[1]", "Tap 'LOGIN'",
                "Wait for error"],
         expected="Error shown: 'The username or password is incorrect.'",
         app_text="The username or password is incorrect.",
         automation="Planned"),
    dict(id="MS-08", title="Forgot Password reachable", module="Auth",
         platform="Both", type="Functional", priority="P3", role=ANY,
         precondition="On login screen",
         precondition_steps=["Reach login screen"],
         steps=["Verify 'Forgot Password?' is visible", "Tap 'Forgot Password?'"],
         expected="Forgot-password screen / flow opens",
         app_text="Forgot Password?", automation="Planned"),
    dict(id="MS-11", title="Onboarding carousel — 3 slides dismissable", module="Auth",
         platform="Both", type="Functional", priority="P2", role=ANY,
         precondition="Fresh launch showing carousel (slide 1 'Benefits')",
         precondition_steps=["Fresh install / first launch"],
         steps=["Verify slide 1 'Benefits' visible", "Verify 'Skip' visible",
                "Option A: tap 'Skip'",
                "Option B: swipe left → 'Payroll' → swipe left → 'Time Tracking' → tap \"Let's Begin\"",
                "Wait for 'LOGIN'"],
         expected="Carousel dismissed; login screen shown",
         app_text="Benefits, Payroll, Time Tracking, Skip, Let's Begin",
         automation="Planned"),
    dict(id="MS-13", title="System permission dialogs handled", module="Auth",
         platform="Both", type="Functional", priority="P2", role=ANY,
         precondition="Fresh install launch (notification prompt)",
         precondition_steps=["Fresh install"],
         steps=["On notification permission tap 'Allow' / 'While using the app'",
                "Verify 'LOGIN' or 'Time Tracking' visible (not blocked)"],
         expected="OS permission dialogs don't block the app",
         app_text="Allow, While using the app, Allow While Using App (iOS)",
         automation="Automated (handled in login flow)"),
    dict(id="MS-14", title="App Lock prompt dismiss", module="Auth",
         platform="Both", type="Functional", priority="P2", role=ANY,
         precondition="Just authenticated (App Lock prompt appears)",
         precondition_steps=LOGGED_IN[:5],
         steps=["Verify 'Enable App Lock' visible",
                "Tap \"I'll do it later\" (matched via contains 'do it later')",
                "Verify dashboard / 'Time Tracking' visible"],
         expected="App Lock prompt dismissed; dashboard reached",
         app_text="Enable App Lock, I'll do it later",
         automation="Automated (login flow)"),
    # ── NAVIGATION ────────────────────────────────────────────────────────
    dict(id="MS-03", title="Bottom navigation — gated tabs reachable", module="Navigation",
         platform="Both", type="Sanity", priority="P1", role=ANY,
         precondition="Logged in",
         precondition_steps=LOGGED_IN,
         steps=["Dismiss any location dialog covering nav",
                "Tap 'Time Tracking'", "Tap 'Benefits' if present",
                "Tap 'Schedule' if present", "Tap 'Time Off' if present",
                "Tap 'Inbox' if present", "Return to 'Time Tracking'"],
         expected="Each feature-gated tab opens its screen",
         app_text="Benefits, Schedule, Time Tracking, Time Off, Inbox",
         automation="Automated · test_ms03_bottom_navigation"),
    dict(id="MS-15", title="Side drawer opens via hamburger", module="Navigation",
         platform="Both", type="Sanity", priority="P1", role=ANY,
         precondition="Logged in, on a main tab",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer (tap hamburger 'menu-sharp', top-left; ~11%/10% Android, ~7%/7% iOS)",
                "Verify a drawer item visible (Logout / My Timesheet / Pay Stubs)"],
         expected="Side drawer opens showing menu sections",
         app_text="menu-sharp, Logout, My Timesheet",
         automation="Automated (exercised by MS-12 and nav tests)"),
    dict(id="MS-16", title="Drawer sections & items render", module="Navigation",
         platform="Both", type="Functional", priority="P2", role=MGR,
         precondition="Drawer open",
         precondition_steps=LOGGED_IN + ["Open drawer"],
         steps=["Reset drawer to top (swipe down)", "Scroll through the drawer",
                "Verify section headers / items: MANAGE TEAM, TIME AND ATTENDANCE, PAY, Logout"],
         expected="Drawer shows the employer's gated sections and items",
         app_text="MANAGE TEAM, TIME AND ATTENDANCE, PAY, Logout",
         automation="Planned"),
    # ── TIME TRACKING ───────────────────────────────────────────────────────
    dict(id="MS-04", title="Time Tracking screen loads", module="Time Tracking",
         platform="Both", type="Sanity", priority="P1", role=ANY,
         precondition="Logged in",
         precondition_steps=ON_TT,
         steps=["Verify 'Clock In' OR 'Clock Out' button visible"],
         expected="Time Tracking screen renders with a clock control",
         app_text="Clock In, Clock Out, Break Time",
         automation="Automated · test_ms04_time_tracking_screen"),
    dict(id="MS-09", title="Clock In — clocked-in state confirmed", module="Time Tracking",
         platform="Both", type="Sanity", priority="P1", role=ANY,
         precondition="Employee clocked OUT",
         precondition_steps=ON_TT + ["If 'Clock Out' visible, clock out first to reset"],
         steps=["Tap 'Clock In'",
                "Close 'You are Clocked In' modal via 'Close'",
                "Wait for 'Clocked In' / 'Clock Out' to appear",
                "Verify clocked-in state"],
         expected="App shows clocked-in state (Clock Out button / 'Clocked In')",
         app_text="Clock In, You are Clocked In, Close, Clocked In",
         automation="Automated · test_ms09_clock_in"),
    dict(id="MS-10", title="Clock Out (with attestation modal)", module="Time Tracking",
         platform="Both", type="Sanity", priority="P1", role=ANY,
         precondition="Employee clocked IN",
         precondition_steps=ON_TT + ["Ensure clocked in (clock in if needed)"],
         steps=["Tap 'Clock Out'",
                "If attestation modal appears: check 'I have reviewed my time…', "
                "select 'Yes, I had the opportunity, but I freely choose not to take this break.', "
                "tap 'Save and Clock Out'",
                "Close 'You are Clocked Out' modal via 'Close'",
                "Wait for 'Clock In' to appear", "Verify clocked-out state"],
         expected="Employee clocked out; attestation (HTTP 428) handled",
         app_text="Clock Out, Time Attestation, Save and Clock Out, You are Clocked Out",
         automation="Automated · test_ms10_clock_out"),
    dict(id="MS-17", title="Break Time — start & end break", module="Time Tracking",
         platform="Both", type="Functional", priority="P2", role=ANY,
         precondition="Employee clocked IN",
         precondition_steps=ON_TT + ["Clock in"],
         steps=["Tap 'Break Time'", "Close 'You are on Break' modal",
                "Verify 'End Break' / 'You are on Break'", "Tap 'End Break'",
                "Close 'Break has Ended' modal"],
         expected="Break starts and ends; states reflected",
         app_text="Break Time, You are on Break, End Break, Break has Ended",
         automation="Planned (needs TimeTrackingPage.start_break/end_break)"),
    dict(id="MS-18", title="Add Time Entry screen opens", module="Time Tracking",
         platform="Both", type="Functional", priority="P2", role=EE_MANUAL,
         precondition="On Time Tracking screen",
         precondition_steps=ON_TT,
         steps=["Tap 'Add Time Entry'", "Verify 'Add Time Entry' screen",
                "Press back"],
         expected="Add-time-entry screen opens",
         app_text="Add Time Entry", automation="Planned"),
    dict(id="MS-19", title="My Timesheet loads (drawer)", module="Time Tracking",
         platform="Both", type="Functional", priority="P2", role=ANY,
         precondition="Logged in",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Scroll to 'My Timesheet'", "Tap 'My Timesheet'",
                "Verify 'My Timesheet' screen"],
         expected="My Timesheet screen loads",
         app_text="My Timesheet, Awaiting Approval",
         automation="Automated · test_ms19_my_timesheet"),
    # ── TIME OFF ──────────────────────────────────────────────────────────
    dict(id="MS-20", title="Time Off screen loads", module="Time Off",
         platform="Both", type="Sanity", priority="P1", role=ANY,
         precondition="Logged in, Time Off feature enabled",
         precondition_steps=LOGGED_IN,
         steps=["Tap 'Time Off' tab",
                "Verify 'Available' OR 'Request Time Off' visible",
                "Tap status tabs if present (Upcoming/Pending/Completed)"],
         expected="Time Off screen renders with status tabs",
         app_text="Available, Upcoming, Pending, Completed, Request Time Off",
         automation="Automated · test_ms20_time_off_screen"),
    dict(id="MS-21", title="Request Time Off flow reachable", module="Time Off",
         platform="Both", type="Functional", priority="P2", role=EE_MOD,
         precondition="On Time Off screen",
         precondition_steps=LOGGED_IN + ["Tap 'Time Off'"],
         steps=["Tap 'Request Time Off'",
                "Verify 'Select Time Off Type' OR 'Start Date' visible", "Press back"],
         expected="Request-time-off form opens",
         app_text="Request Time Off, Select Time Off Type, Start Date",
         automation="Planned"),
    dict(id="MS-22", title="Time Off History loads (drawer)", module="Time Off",
         platform="Both", type="Functional", priority="P2", role=ANY,
         precondition="Logged in",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Scroll to 'Time Off History'", "Tap it",
                "Verify 'Time Off History' screen"],
         expected="Time Off History screen loads",
         app_text="Time Off History",
         automation="Automated · test_ms22_time_off_history"),
    dict(id="MS-23", title="Holiday Calendar loads (drawer)", module="Time Off",
         platform="Both", type="Functional", priority="P3", role=ANY,
         precondition="Logged in",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Scroll to 'Holiday Calendar'", "Tap it",
                "Verify 'Holiday Calendar' screen"],
         expected="Holiday Calendar loads",
         app_text="Holiday Calendar",
         automation="Automated · test_ms23_holiday_calendar"),
    # ── SCHEDULE ──────────────────────────────────────────────────────────
    dict(id="MS-24", title="Schedule screen loads", module="Schedule",
         platform="Both", type="Functional", priority="P2", role=ANY,
         precondition="Logged in, Schedule feature enabled",
         precondition_steps=LOGGED_IN,
         steps=["Tap 'Schedule' tab",
                "Verify 'My Upcoming Schedule' / 'No Shift' / 'View Full Schedule'"],
         expected="Schedule screen renders",
         app_text="My Upcoming Schedule, No Shift, View Full Schedule",
         automation="Automated · test_ms24_schedule_screen"),
    dict(id="MS-25", title="View Full Schedule reachable", module="Schedule",
         platform="Both", type="Functional", priority="P3", role=ANY,
         precondition="On Schedule screen",
         precondition_steps=LOGGED_IN + ["Tap 'Schedule'"],
         steps=["Tap 'View Full Schedule'", "Press back"],
         expected="Full schedule view opens",
         app_text="View Full Schedule", automation="Planned"),
    # ── BENEFITS ──────────────────────────────────────────────────────────
    dict(id="MS-26", title="Benefits screen loads", module="Benefits",
         platform="Both", type="Sanity", priority="P1", role=ANY,
         precondition="Logged in",
         precondition_steps=LOGGED_IN,
         steps=["Tap 'Benefits' tab",
                "Verify 'Current' / 'Plan Documents' / 'Benefits'",
                "Tap status tabs if present (Pending/Upcoming)"],
         expected="Benefits screen renders with status tabs",
         app_text="Benefits, Current, Pending, Upcoming, Plan Documents",
         automation="Automated · test_ms26_benefits_screen"),
    dict(id="MS-27", title="Benefits Plan Documents accessible", module="Benefits",
         platform="Both", type="Functional", priority="P3", role=ANY,
         precondition="On Benefits screen",
         precondition_steps=LOGGED_IN + ["Tap 'Benefits'"],
         steps=["Scroll to 'Plan Documents'", "Verify 'Plan Documents' visible"],
         expected="Plan Documents section visible",
         app_text="Plan Documents", automation="Planned"),
    # ── PAY / PAYROLL ───────────────────────────────────────────────────────
    dict(id="MS-28", title="Pay Stubs loads (drawer)", module="Pay",
         platform="Both", type="Sanity", priority="P1", role=ANY,
         precondition="Logged in, Uzio Payroll enabled",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Scroll to 'Pay Stubs'", "Tap it",
                "Verify 'Pay Stubs' / 'Net Pay' / 'Pay Period'"],
         expected="Pay Stubs screen loads",
         app_text="Pay Stubs, Net Pay, Pay Period",
         automation="Automated · test_ms28_pay_stubs"),
    dict(id="MS-29", title="Payment Method loads (drawer)", module="Pay",
         platform="Both", type="Functional", priority="P2", role=ANY,
         precondition="Logged in, payroll enabled",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Scroll to 'Payment Method'", "Tap it",
                "Verify 'Payment Method' / 'Direct Deposit'",
                "SECURITY: do NOT enter bank/routing numbers"],
         expected="Payment Method screen loads (read-only verify)",
         app_text="Payment Method, Direct Deposit",
         automation="Automated · test_ms29_payment_method"),
    dict(id="MS-30", title="W-2 Forms loads (drawer)", module="Pay",
         platform="Both", type="Functional", priority="P2", role=ANY,
         precondition="Logged in, payroll enabled",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Scroll to 'W-2 Forms'", "Tap it",
                "Verify 'W-2 Forms' / 'No W-2 Forms are Available'"],
         expected="W-2 Forms screen loads",
         app_text="W-2 Forms, No W-2 Forms are Available",
         automation="Automated · test_ms30_w2_forms"),
    dict(id="MS-31", title="Federal Tax Withholding loads (drawer)", module="Pay",
         platform="Both", type="Functional", priority="P3", role=ANY,
         precondition="Logged in, payroll enabled",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Scroll to 'Federal Tax Withholding'", "Tap it",
                "Verify 'Federal Tax Withholding' / 'Filing Status'",
                "SECURITY: do NOT enter SSN/tax data"],
         expected="Federal Tax Withholding screen loads (read-only verify)",
         app_text="Federal Tax Withholding, Filing Status",
         automation="Automated · test_ms31_federal_tax"),
    # ── PERSONAL ──────────────────────────────────────────────────────────
    dict(id="MS-32", title="My Info / Profile loads (drawer)", module="Personal",
         platform="Both", type="Functional", priority="P2", role=ANY,
         precondition="Logged in",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Scroll to 'My Info'", "Tap it",
                "Verify 'My Info' / 'Personal Details'"],
         expected="My Info screen loads",
         app_text="My Info, Personal Details",
         automation="Automated · test_ms32_my_info (skips if absent)"),
    dict(id="MS-33", title="Documents loads (drawer)", module="Personal",
         platform="Both", type="Functional", priority="P2", role=ANY,
         precondition="Logged in",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Scroll to 'Documents'", "Tap it",
                "Verify 'Documents' screen"],
         expected="Documents screen loads",
         app_text="Documents", automation="Automated · test_ms33_documents"),
    dict(id="MS-34", title="Tasks loads (drawer)", module="Personal",
         platform="Both", type="Functional", priority="P2", role=ANY,
         precondition="Logged in",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Scroll to 'Tasks'", "Tap it",
                "Verify 'Tasks' / 'Pending'"],
         expected="Tasks screen loads with tabs",
         app_text="Tasks, Pending, Completed",
         automation="Automated · test_ms34_tasks"),
    dict(id="MS-35", title="Resources loads (drawer)", module="Personal",
         platform="Both", type="Functional", priority="P3", role=ANY,
         precondition="Logged in",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Scroll to 'Resources'", "Tap it",
                "Verify 'Resources' screen"],
         expected="Resources screen loads",
         app_text="Resources", automation="Planned"),
    # ── INBOX ─────────────────────────────────────────────────────────────
    dict(id="MS-36", title="Inbox loads", module="Inbox",
         platform="Both", type="Sanity", priority="P1", role=ANY,
         precondition="Logged in",
         precondition_steps=LOGGED_IN,
         steps=["Tap 'Inbox' tab",
                "Verify 'Your Action Needed' / 'Notifications' / 'No Notifications Available'"],
         expected="Inbox screen renders with tabs",
         app_text="Inbox, Your Action Needed, Notifications, No Notifications Available",
         automation="Automated · test_ms36_inbox_screen"),
    # ── MANAGER (MANAGE TEAM) ───────────────────────────────────────────────
    dict(id="MS-37", title="Team Timesheet loads (manager)", module="Manager",
         platform="Both", type="Functional", priority="P2", role=MGR,
         precondition="Logged in as a manager",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Scroll to 'Team Timesheet'", "Tap it",
                "Verify 'Team Timesheet' screen"],
         expected="Team Timesheet loads (manager only)",
         app_text="Team Timesheet",
         automation="Automated · test_ms37_team_timesheet (skips if absent)"),
    dict(id="MS-38", title="Team Time Off loads (manager)", module="Manager",
         platform="Both", type="Functional", priority="P2", role=MGR,
         precondition="Logged in as a manager",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Scroll to 'Team Time Off'", "Tap it",
                "Verify 'Team Time Off' / \"Who's out during this period\""],
         expected="Team Time Off loads (manager only)",
         app_text="Team Time Off, Who's out during this period",
         automation="Automated · test_ms38_team_time_off (skips if absent)"),
    # ── SETTINGS / ACCOUNT ──────────────────────────────────────────────────
    dict(id="MS-39", title="Account Information expands", module="Settings",
         platform="Both", type="Functional", priority="P3", role=ANY,
         precondition="Logged in",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Scroll to 'Account Information'", "Tap to expand",
                "Verify 'Login Accounts' / '2-Step Verification'"],
         expected="Account Information dropdown expands",
         app_text="Account Information, Login Accounts, 2-Step Verification",
         automation="Planned"),
    dict(id="MS-40", title="Contact Support / Help Center present", module="Settings",
         platform="Both", type="Functional", priority="P3", role=ANY,
         precondition="Logged in",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Scroll to 'Contact Support'",
                "Verify 'Contact Support' (and 'Help Center' if present)"],
         expected="Help & Support entries present",
         app_text="Contact Support, Help Center", automation="Planned"),
    # ── SESSION ─────────────────────────────────────────────────────────────
    dict(id="MS-12", title="Logout via hamburger drawer", module="Session",
         platform="Both", type="Sanity", priority="P1", role=ANY,
         precondition="Logged in",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Scroll to 'Logout'", "Tap 'Logout'",
                "Confirm dialog if present (Yes/Confirm)",
                "Dismiss onboarding carousel if it reappears",
                "Wait for 'LOGIN'"],
         expected="Returns to login screen (carousel may show first)",
         app_text="Logout, LOGIN",
         automation="Automated · test_ms12_logout"),
    dict(id="MS-41", title="Company switch (multi-company)", module="Session",
         platform="Both", type="Functional", priority="P3", role=MGR,
         precondition="User linked to 2+ companies",
         precondition_steps=LOGGED_IN,
         steps=["Open drawer", "Tap the company-name dropdown (drawer header)",
                "Verify a second company option visible", "Press back"],
         expected="Company switcher lists multiple companies",
         app_text="(employer name dropdown)", automation="Planned"),
    dict(id="MS-42", title="Session persistence on relaunch", module="Session",
         platform="Both", type="Functional", priority="P2", role=ANY,
         precondition="Logged in once (no_reset)",
         precondition_steps=LOGGED_IN,
         steps=["Relaunch app (driver, no_reset=true)",
                "Dismiss 'Enable App Lock' / permissions",
                "Verify 'Time Tracking' visible (no login needed)"],
         expected="Session retained; straight to dashboard",
         app_text="Time Tracking",
         automation="Automated (login already-logged-in path)"),
    # ── RESILIENCE ──────────────────────────────────────────────────────────
    dict(id="MS-43", title="Offline / no-internet handling", module="Resilience",
         platform="Both", type="Edge", priority="P3", role=ANY,
         precondition="Logged in; network can be toggled",
         precondition_steps=LOGGED_IN,
         steps=["Disable network (airplane mode / driver)", "Tap 'Clock In'",
                "Verify 'No Internet. Please try again later.' / 'No Internet Connection'",
                "Re-enable network"],
         expected="Graceful no-internet message, no crash",
         app_text="No Internet. Please try again later., No Internet Connection",
         automation="Planned (needs network toggle)"),
]

META = dict(
    title="UZIO Mobile — Sanity Test Cases",
    source="tests/sanity/sanity.test.md",
    generated_by="Test Generation Agent (MobileAutoQA)",
    environment="QA (teamadmin) / PROD",
    app_build="TA 21-05-2026 / PROD 22-05-2026",
    notes=("Mobile sanity smoke suite — critical path of every major feature. "
           "App has NO testIDs: all locators are visible i18n text. "
           "Roles: mobile2@t.com=Manager, mobile1@t.com=EE(manual), mobile3@t.com=EE(modify/reportee). "
           "SECURITY: Pay/Tax screens verify LOAD only — never enter bank/SSN data. "
           "Automated cases run via pytest tests/sanity; 'Planned' need new page objects."),
)

if __name__ == "__main__":
    out = build_testcase_workbook(
        "reports/testcases/UZIO_Mobile_Sanity_Testcases.xlsx", META, CASES)
    print(f"[gen] {len(CASES)} test cases -> {out}")
